// GENERATED by tools/levelgen/bake.js — do not edit by hand.
//
// The DAILY DECK's generated half. POOL: levels dealt only by the daily —
// twins of levels 1-12 by construction, which is why they are not in LEVELS
// and why that does not matter where the challenge is the ink. POOL_SOLVER:
// their numbers, measured by the same sweep that writes js/solverData.js.
// HELD_FROM_DAILY: campaign levels with no hand-drawn win inside their daily
// budget, and the measurement that says so. They stay in the campaign.
//
// Re-bake after any physics change or campaign change: none of this
// re-measures itself, and tools/test/daily-deck.js fails until it is redone.
// Re-baking can change which levels the deck holds, and any change to the
// deck reshuffles EVERY future day. Do it before launch, not after.

export const POOL = [
  {
    "verb": "CHOOSE",
    "hint": "KEEP IT OFF HIM",
    "milo": {
      "start": {
        "x": 70,
        "y": 1144
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 660,
      "y": 1144,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1144,
        "w": 720,
        "h": 136
      },
      {
        "id": "chimL",
        "type": "platform",
        "x": 260,
        "y": 400,
        "w": 30,
        "h": 410
      },
      {
        "id": "chimR",
        "type": "platform",
        "x": 380,
        "y": 400,
        "w": 30,
        "h": 410
      },
      {
        "id": "shelf",
        "type": "platform",
        "x": 440,
        "y": 1030,
        "w": 200,
        "h": 26
      }
    ],
    "objects": [
      {
        "id": "rock",
        "type": "boulder",
        "x": 315,
        "y": 450,
        "radius": 24,
        "density": 0.03,
        "restitution": 0.06,
        "friction": 0.35,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-chimney-174219",
    "world": "backyard",
    "solver": null,
    "freezeAt": 530,
    "generated": {
      "archetype": "chimney",
      "seed": 174219
    }
  },
  {
    "verb": "BRIDGE",
    "hint": "GET HIM ACROSS",
    "milo": {
      "start": {
        "x": 70,
        "y": 930
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 600,
      "y": 1050,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "bankL",
        "type": "platform",
        "x": 0,
        "y": 930,
        "w": 300,
        "h": 350
      },
      {
        "id": "bankR",
        "type": "platform",
        "x": 470,
        "y": 1050,
        "w": 250,
        "h": 230
      }
    ],
    "objects": [],
    "zones": [
      {
        "id": "pit",
        "kind": "zone",
        "x": 305,
        "y": 1215,
        "w": 160,
        "h": 65,
        "lethal": true
      }
    ],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-crossing-31677",
    "world": "backyard",
    "solver": null,
    "freezeAt": 900,
    "generated": {
      "archetype": "crossing",
      "seed": 31677
    }
  },
  {
    "verb": "BLOCK",
    "hint": "IT WILL DROP ON HIM",
    "milo": {
      "start": {
        "x": 130,
        "y": 1096
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 660,
      "y": 1096,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1096,
        "w": 720,
        "h": 184
      },
      {
        "id": "shelfL",
        "type": "platform",
        "x": 190,
        "y": 740,
        "w": 100,
        "h": 28
      },
      {
        "id": "shelfR",
        "type": "platform",
        "x": 390,
        "y": 740,
        "w": 100,
        "h": 28
      }
    ],
    "objects": [
      {
        "id": "rock",
        "type": "boulder",
        "x": 340,
        "y": 300,
        "radius": 28,
        "density": 0.03,
        "restitution": 0.06,
        "friction": 0.4,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-drop-23758",
    "world": "backyard",
    "solver": null,
    "freezeAt": 580,
    "generated": {
      "archetype": "drop",
      "seed": 23758
    }
  },
  {
    "verb": "INTERCEPT",
    "hint": "STOP THE ROLLER",
    "milo": {
      "start": {
        "x": 70,
        "y": 1160
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 665,
      "y": 1160,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1160,
        "w": 720,
        "h": 120
      },
      {
        "id": "ledge",
        "type": "platform",
        "x": 520,
        "y": 890,
        "w": 200,
        "h": 30
      }
    ],
    "objects": [
      {
        "id": "roller",
        "type": "boulder",
        "x": 660,
        "y": 856,
        "radius": 34,
        "density": 0.04,
        "restitution": 0.05,
        "friction": 0.15,
        "frictionAir": 0,
        "vx": -220,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 560,
      "denyZones": []
    },
    "id": "gen-roller-87110",
    "world": "backyard",
    "solver": null,
    "freezeAt": 810,
    "generated": {
      "archetype": "roller",
      "seed": 87110
    }
  },
  {
    "verb": "TRIGGER",
    "hint": "THE PLATE OPENS THE GATE",
    "milo": {
      "start": {
        "x": 80,
        "y": 1136
      },
      "speed": 190
    },
    "goal": {
      "id": "goal",
      "x": 665,
      "y": 1136,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1136,
        "w": 720,
        "h": 144
      },
      {
        "id": "shelf",
        "type": "platform",
        "x": 280,
        "y": 840,
        "w": 200,
        "h": 26
      },
      {
        "id": "lip",
        "type": "platform",
        "x": 180,
        "y": 640,
        "w": 120,
        "h": 26
      }
    ],
    "objects": [
      {
        "id": "rock",
        "type": "boulder",
        "x": 280,
        "y": 240,
        "radius": 26,
        "density": 0.03,
        "restitution": 0.08,
        "friction": 0.4,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      },
      {
        "id": "plate",
        "type": "switch",
        "x": 300,
        "y": 808,
        "w": 160,
        "h": 32,
        "triggers": [
          "gate"
        ]
      },
      {
        "id": "gate",
        "type": "gate",
        "x": 540,
        "y": 996,
        "w": 34,
        "h": 140
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-trigger-7920",
    "world": "backyard",
    "solver": null,
    "freezeAt": 900,
    "generated": {
      "archetype": "trigger",
      "seed": 7920
    }
  },
  {
    "verb": "CHOOSE",
    "hint": "KEEP IT OFF HIM",
    "milo": {
      "start": {
        "x": 90,
        "y": 1120
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 660,
      "y": 1120,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1120,
        "w": 720,
        "h": 160
      },
      {
        "id": "chimL",
        "type": "platform",
        "x": 210,
        "y": 420,
        "w": 30,
        "h": 380
      },
      {
        "id": "chimR",
        "type": "platform",
        "x": 400,
        "y": 420,
        "w": 30,
        "h": 380
      },
      {
        "id": "shelf",
        "type": "platform",
        "x": 470,
        "y": 960,
        "w": 200,
        "h": 26
      }
    ],
    "objects": [
      {
        "id": "rock",
        "type": "boulder",
        "x": 325,
        "y": 490,
        "radius": 28,
        "density": 0.03,
        "restitution": 0.06,
        "friction": 0.35,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-chimney-245490",
    "world": "backyard",
    "solver": null,
    "freezeAt": 490,
    "generated": {
      "archetype": "chimney",
      "seed": 245490
    }
  },
  {
    "verb": "BRIDGE",
    "hint": "GET HIM ACROSS",
    "milo": {
      "start": {
        "x": 100,
        "y": 970
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 590,
      "y": 1110,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "bankL",
        "type": "platform",
        "x": 0,
        "y": 970,
        "w": 330,
        "h": 310
      },
      {
        "id": "bankR",
        "type": "platform",
        "x": 460,
        "y": 1110,
        "w": 260,
        "h": 170
      }
    ],
    "objects": [],
    "zones": [
      {
        "id": "pit",
        "kind": "zone",
        "x": 335,
        "y": 1215,
        "w": 120,
        "h": 65,
        "lethal": true
      }
    ],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-crossing-174219",
    "world": "backyard",
    "solver": null,
    "freezeAt": 900,
    "generated": {
      "archetype": "crossing",
      "seed": 174219
    }
  },
  {
    "verb": "BLOCK",
    "hint": "IT WILL DROP ON HIM",
    "milo": {
      "start": {
        "x": 150,
        "y": 1112
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 640,
      "y": 1112,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1112,
        "w": 720,
        "h": 168
      },
      {
        "id": "shelfL",
        "type": "platform",
        "x": 225,
        "y": 780,
        "w": 130,
        "h": 28
      },
      {
        "id": "shelfR",
        "type": "platform",
        "x": 505,
        "y": 780,
        "w": 130,
        "h": 28
      }
    ],
    "objects": [
      {
        "id": "rock",
        "type": "boulder",
        "x": 430,
        "y": 310,
        "radius": 28,
        "density": 0.03,
        "restitution": 0.06,
        "friction": 0.4,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-drop-39596",
    "world": "backyard",
    "solver": null,
    "freezeAt": 600,
    "generated": {
      "archetype": "drop",
      "seed": 39596
    }
  },
  {
    "verb": "INTERCEPT",
    "hint": "STOP THE ROLLER",
    "milo": {
      "start": {
        "x": 70,
        "y": 1152
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 665,
      "y": 1152,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1152,
        "w": 720,
        "h": 128
      },
      {
        "id": "ledge",
        "type": "platform",
        "x": 460,
        "y": 930,
        "w": 260,
        "h": 30
      }
    ],
    "objects": [
      {
        "id": "roller",
        "type": "boulder",
        "x": 630,
        "y": 896,
        "radius": 34,
        "density": 0.04,
        "restitution": 0.05,
        "friction": 0.15,
        "frictionAir": 0,
        "vx": -340,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 500,
      "denyZones": []
    },
    "id": "gen-roller-182138",
    "world": "backyard",
    "solver": null,
    "freezeAt": 650,
    "generated": {
      "archetype": "roller",
      "seed": 182138
    }
  },
  {
    "verb": "TRIGGER",
    "hint": "THE PLATE OPENS THE GATE",
    "milo": {
      "start": {
        "x": 80,
        "y": 1152
      },
      "speed": 210
    },
    "goal": {
      "id": "goal",
      "x": 665,
      "y": 1152,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1152,
        "w": 720,
        "h": 128
      },
      {
        "id": "shelf",
        "type": "platform",
        "x": 300,
        "y": 760,
        "w": 210,
        "h": 26
      },
      {
        "id": "lip",
        "type": "platform",
        "x": 130,
        "y": 680,
        "w": 130,
        "h": 26
      }
    ],
    "objects": [
      {
        "id": "rock",
        "type": "boulder",
        "x": 290,
        "y": 250,
        "radius": 26,
        "density": 0.03,
        "restitution": 0.08,
        "friction": 0.4,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      },
      {
        "id": "plate",
        "type": "switch",
        "x": 320,
        "y": 728,
        "w": 160,
        "h": 32,
        "triggers": [
          "gate"
        ]
      },
      {
        "id": "gate",
        "type": "gate",
        "x": 540,
        "y": 1012,
        "w": 34,
        "h": 140
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-trigger-71272",
    "world": "backyard",
    "solver": null,
    "freezeAt": 900,
    "generated": {
      "archetype": "trigger",
      "seed": 71272
    }
  },
  {
    "verb": "CHOOSE",
    "hint": "KEEP IT OFF HIM",
    "milo": {
      "start": {
        "x": 80,
        "y": 1160
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 660,
      "y": 1160,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1160,
        "w": 720,
        "h": 120
      },
      {
        "id": "chimL",
        "type": "platform",
        "x": 240,
        "y": 340,
        "w": 30,
        "h": 430
      },
      {
        "id": "chimR",
        "type": "platform",
        "x": 410,
        "y": 340,
        "w": 30,
        "h": 430
      },
      {
        "id": "shelf",
        "type": "platform",
        "x": 500,
        "y": 1040,
        "w": 200,
        "h": 26
      }
    ],
    "objects": [
      {
        "id": "rock",
        "type": "boulder",
        "x": 340,
        "y": 380,
        "radius": 26,
        "density": 0.03,
        "restitution": 0.06,
        "friction": 0.35,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-chimney-197976",
    "world": "backyard",
    "solver": null,
    "freezeAt": 580,
    "generated": {
      "archetype": "chimney",
      "seed": 197976
    }
  },
  {
    "verb": "BRIDGE",
    "hint": "GET HIM ACROSS",
    "milo": {
      "start": {
        "x": 90,
        "y": 900
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 660,
      "y": 1040,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "bankL",
        "type": "platform",
        "x": 0,
        "y": 900,
        "w": 340,
        "h": 380
      },
      {
        "id": "bankR",
        "type": "platform",
        "x": 530,
        "y": 1040,
        "w": 190,
        "h": 240
      }
    ],
    "objects": [],
    "zones": [
      {
        "id": "pit",
        "kind": "zone",
        "x": 345,
        "y": 1215,
        "w": 180,
        "h": 65,
        "lethal": true
      }
    ],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-crossing-118786",
    "world": "backyard",
    "solver": null,
    "freezeAt": 900,
    "generated": {
      "archetype": "crossing",
      "seed": 118786
    }
  },
  {
    "verb": "BLOCK",
    "hint": "IT WILL DROP ON HIM",
    "milo": {
      "start": {
        "x": 120,
        "y": 1096
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 640,
      "y": 1096,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1096,
        "w": 720,
        "h": 184
      },
      {
        "id": "shelfL",
        "type": "platform",
        "x": 215,
        "y": 730,
        "w": 110,
        "h": 28
      },
      {
        "id": "shelfR",
        "type": "platform",
        "x": 435,
        "y": 730,
        "w": 110,
        "h": 28
      }
    ],
    "objects": [
      {
        "id": "rock",
        "type": "boulder",
        "x": 380,
        "y": 340,
        "radius": 24,
        "density": 0.03,
        "restitution": 0.06,
        "friction": 0.4,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-drop-142543",
    "world": "backyard",
    "solver": null,
    "freezeAt": 560,
    "generated": {
      "archetype": "drop",
      "seed": 142543
    }
  },
  {
    "verb": "INTERCEPT",
    "hint": "STOP THE ROLLER",
    "milo": {
      "start": {
        "x": 110,
        "y": 1136
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 665,
      "y": 1136,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1136,
        "w": 720,
        "h": 144
      },
      {
        "id": "ledge",
        "type": "platform",
        "x": 500,
        "y": 840,
        "w": 220,
        "h": 30
      }
    ],
    "objects": [
      {
        "id": "roller",
        "type": "boulder",
        "x": 670,
        "y": 806,
        "radius": 34,
        "density": 0.04,
        "restitution": 0.05,
        "friction": 0.15,
        "frictionAir": 0,
        "vx": -260,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 460,
      "denyZones": []
    },
    "id": "gen-roller-158381",
    "world": "backyard",
    "solver": null,
    "freezeAt": 830,
    "generated": {
      "archetype": "roller",
      "seed": 158381
    }
  },
  {
    "verb": "TRIGGER",
    "hint": "THE PLATE OPENS THE GATE",
    "milo": {
      "start": {
        "x": 90,
        "y": 1136
      },
      "speed": 200
    },
    "goal": {
      "id": "goal",
      "x": 665,
      "y": 1136,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1136,
        "w": 720,
        "h": 144
      },
      {
        "id": "shelf",
        "type": "platform",
        "x": 230,
        "y": 900,
        "w": 210,
        "h": 26
      },
      {
        "id": "lip",
        "type": "platform",
        "x": 170,
        "y": 630,
        "w": 140,
        "h": 26
      }
    ],
    "objects": [
      {
        "id": "rock",
        "type": "boulder",
        "x": 300,
        "y": 260,
        "radius": 26,
        "density": 0.03,
        "restitution": 0.08,
        "friction": 0.4,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      },
      {
        "id": "plate",
        "type": "switch",
        "x": 250,
        "y": 868,
        "w": 160,
        "h": 32,
        "triggers": [
          "gate"
        ]
      },
      {
        "id": "gate",
        "type": "gate",
        "x": 540,
        "y": 996,
        "w": 34,
        "h": 140
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-trigger-134624",
    "world": "backyard",
    "solver": null,
    "freezeAt": 900,
    "generated": {
      "archetype": "trigger",
      "seed": 134624
    }
  },
  {
    "verb": "CHOOSE",
    "hint": "KEEP IT OFF HIM",
    "milo": {
      "start": {
        "x": 100,
        "y": 1144
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 660,
      "y": 1144,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1144,
        "w": 720,
        "h": 136
      },
      {
        "id": "chimL",
        "type": "platform",
        "x": 230,
        "y": 390,
        "w": 30,
        "h": 430
      },
      {
        "id": "chimR",
        "type": "platform",
        "x": 410,
        "y": 390,
        "w": 30,
        "h": 430
      },
      {
        "id": "shelf",
        "type": "platform",
        "x": 550,
        "y": 1030,
        "w": 170,
        "h": 26
      }
    ],
    "objects": [
      {
        "id": "rock",
        "type": "boulder",
        "x": 335,
        "y": 440,
        "radius": 24,
        "density": 0.03,
        "restitution": 0.06,
        "friction": 0.35,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-chimney-166300",
    "world": "backyard",
    "solver": null,
    "freezeAt": 530,
    "generated": {
      "archetype": "chimney",
      "seed": 166300
    }
  },
  {
    "verb": "BRIDGE",
    "hint": "GET HIM ACROSS",
    "milo": {
      "start": {
        "x": 120,
        "y": 940
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 630,
      "y": 1120,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "bankL",
        "type": "platform",
        "x": 0,
        "y": 940,
        "w": 310,
        "h": 340
      },
      {
        "id": "bankR",
        "type": "platform",
        "x": 500,
        "y": 1120,
        "w": 220,
        "h": 160
      }
    ],
    "objects": [],
    "zones": [
      {
        "id": "pit",
        "kind": "zone",
        "x": 315,
        "y": 1215,
        "w": 180,
        "h": 65,
        "lethal": true
      }
    ],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-crossing-39596",
    "world": "backyard",
    "solver": null,
    "freezeAt": 900,
    "generated": {
      "archetype": "crossing",
      "seed": 39596
    }
  },
  {
    "verb": "BLOCK",
    "hint": "IT WILL DROP ON HIM",
    "milo": {
      "start": {
        "x": 100,
        "y": 1072
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 650,
      "y": 1072,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1072,
        "w": 720,
        "h": 208
      },
      {
        "id": "shelfL",
        "type": "platform",
        "x": 205,
        "y": 830,
        "w": 80,
        "h": 28
      },
      {
        "id": "shelfR",
        "type": "platform",
        "x": 435,
        "y": 830,
        "w": 80,
        "h": 28
      }
    ],
    "objects": [
      {
        "id": "rock",
        "type": "boulder",
        "x": 360,
        "y": 300,
        "radius": 22,
        "density": 0.03,
        "restitution": 0.06,
        "friction": 0.4,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-drop-1",
    "world": "backyard",
    "solver": null,
    "freezeAt": 570,
    "generated": {
      "archetype": "drop",
      "seed": 1
    }
  },
  {
    "verb": "INTERCEPT",
    "hint": "STOP THE ROLLER",
    "milo": {
      "start": {
        "x": 90,
        "y": 1112
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 665,
      "y": 1112,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1112,
        "w": 720,
        "h": 168
      },
      {
        "id": "ledge",
        "type": "platform",
        "x": 480,
        "y": 900,
        "w": 240,
        "h": 30
      }
    ],
    "objects": [
      {
        "id": "roller",
        "type": "boulder",
        "x": 680,
        "y": 866,
        "radius": 34,
        "density": 0.04,
        "restitution": 0.05,
        "friction": 0.15,
        "frictionAir": 0,
        "vx": -300,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 540,
      "denyZones": []
    },
    "id": "gen-roller-229652",
    "world": "backyard",
    "solver": null,
    "freezeAt": 780,
    "generated": {
      "archetype": "roller",
      "seed": 229652
    }
  },
  {
    "verb": "TRIGGER",
    "hint": "THE PLATE OPENS THE GATE",
    "milo": {
      "start": {
        "x": 70,
        "y": 1128
      },
      "speed": 180
    },
    "goal": {
      "id": "goal",
      "x": 665,
      "y": 1128,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1128,
        "w": 720,
        "h": 152
      },
      {
        "id": "shelf",
        "type": "platform",
        "x": 240,
        "y": 780,
        "w": 190,
        "h": 26
      },
      {
        "id": "lip",
        "type": "platform",
        "x": 190,
        "y": 700,
        "w": 130,
        "h": 26
      }
    ],
    "objects": [
      {
        "id": "rock",
        "type": "boulder",
        "x": 270,
        "y": 260,
        "radius": 26,
        "density": 0.03,
        "restitution": 0.08,
        "friction": 0.4,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      },
      {
        "id": "plate",
        "type": "switch",
        "x": 260,
        "y": 748,
        "w": 150,
        "h": 32,
        "triggers": [
          "gate"
        ]
      },
      {
        "id": "gate",
        "type": "gate",
        "x": 520,
        "y": 988,
        "w": 34,
        "h": 140
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-trigger-110867",
    "world": "backyard",
    "solver": null,
    "freezeAt": 900,
    "generated": {
      "archetype": "trigger",
      "seed": 110867
    }
  },
  {
    "verb": "CHOOSE",
    "hint": "KEEP IT OFF HIM",
    "milo": {
      "start": {
        "x": 100,
        "y": 1144
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 660,
      "y": 1144,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1144,
        "w": 720,
        "h": 136
      },
      {
        "id": "chimL",
        "type": "platform",
        "x": 260,
        "y": 420,
        "w": 30,
        "h": 360
      },
      {
        "id": "chimR",
        "type": "platform",
        "x": 390,
        "y": 420,
        "w": 30,
        "h": 360
      },
      {
        "id": "shelf",
        "type": "platform",
        "x": 480,
        "y": 1010,
        "w": 200,
        "h": 26
      }
    ],
    "objects": [
      {
        "id": "rock",
        "type": "boulder",
        "x": 310,
        "y": 470,
        "radius": 26,
        "density": 0.03,
        "restitution": 0.06,
        "friction": 0.35,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-chimney-63353",
    "world": "backyard",
    "solver": null,
    "freezeAt": 530,
    "generated": {
      "archetype": "chimney",
      "seed": 63353
    }
  },
  {
    "verb": "BRIDGE",
    "hint": "GET HIM ACROSS",
    "milo": {
      "start": {
        "x": 90,
        "y": 960
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 670,
      "y": 1040,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "bankL",
        "type": "platform",
        "x": 0,
        "y": 960,
        "w": 330,
        "h": 320
      },
      {
        "id": "bankR",
        "type": "platform",
        "x": 560,
        "y": 1040,
        "w": 160,
        "h": 240
      }
    ],
    "objects": [],
    "zones": [
      {
        "id": "pit",
        "kind": "zone",
        "x": 335,
        "y": 1215,
        "w": 220,
        "h": 65,
        "lethal": true
      }
    ],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-crossing-55434",
    "world": "backyard",
    "solver": null,
    "freezeAt": 900,
    "generated": {
      "archetype": "crossing",
      "seed": 55434
    }
  },
  {
    "verb": "BLOCK",
    "hint": "IT WILL DROP ON HIM",
    "milo": {
      "start": {
        "x": 90,
        "y": 1128
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 630,
      "y": 1128,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1128,
        "w": 720,
        "h": 152
      },
      {
        "id": "shelfL",
        "type": "platform",
        "x": 160,
        "y": 820,
        "w": 100,
        "h": 28
      },
      {
        "id": "shelfR",
        "type": "platform",
        "x": 460,
        "y": 820,
        "w": 100,
        "h": 28
      }
    ],
    "objects": [
      {
        "id": "rock",
        "type": "boulder",
        "x": 360,
        "y": 310,
        "radius": 28,
        "density": 0.03,
        "restitution": 0.06,
        "friction": 0.4,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-drop-55434",
    "world": "backyard",
    "solver": null,
    "freezeAt": 600,
    "generated": {
      "archetype": "drop",
      "seed": 55434
    }
  },
  {
    "verb": "INTERCEPT",
    "hint": "STOP THE ROLLER",
    "milo": {
      "start": {
        "x": 80,
        "y": 1112
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 665,
      "y": 1112,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1112,
        "w": 720,
        "h": 168
      },
      {
        "id": "ledge",
        "type": "platform",
        "x": 480,
        "y": 870,
        "w": 240,
        "h": 30
      }
    ],
    "objects": [
      {
        "id": "roller",
        "type": "boulder",
        "x": 620,
        "y": 836,
        "radius": 34,
        "density": 0.04,
        "restitution": 0.05,
        "friction": 0.15,
        "frictionAir": 0,
        "vx": -300,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 420,
      "denyZones": []
    },
    "id": "gen-roller-110867",
    "world": "backyard",
    "solver": null,
    "freezeAt": 630,
    "generated": {
      "archetype": "roller",
      "seed": 110867
    }
  },
  {
    "verb": "TRIGGER",
    "hint": "THE PLATE OPENS THE GATE",
    "milo": {
      "start": {
        "x": 60,
        "y": 1128
      },
      "speed": 200
    },
    "goal": {
      "id": "goal",
      "x": 665,
      "y": 1128,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1128,
        "w": 720,
        "h": 152
      },
      {
        "id": "shelf",
        "type": "platform",
        "x": 270,
        "y": 820,
        "w": 210,
        "h": 26
      },
      {
        "id": "lip",
        "type": "platform",
        "x": 190,
        "y": 620,
        "w": 130,
        "h": 26
      }
    ],
    "objects": [
      {
        "id": "rock",
        "type": "boulder",
        "x": 340,
        "y": 260,
        "radius": 26,
        "density": 0.03,
        "restitution": 0.08,
        "friction": 0.4,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      },
      {
        "id": "plate",
        "type": "switch",
        "x": 290,
        "y": 788,
        "w": 140,
        "h": 32,
        "triggers": [
          "gate"
        ]
      },
      {
        "id": "gate",
        "type": "gate",
        "x": 530,
        "y": 988,
        "w": 34,
        "h": 140
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-trigger-118786",
    "world": "backyard",
    "solver": null,
    "freezeAt": 900,
    "generated": {
      "archetype": "trigger",
      "seed": 118786
    }
  },
  {
    "verb": "CHOOSE",
    "hint": "KEEP IT OFF HIM",
    "milo": {
      "start": {
        "x": 110,
        "y": 1152
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 660,
      "y": 1152,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1152,
        "w": 720,
        "h": 128
      },
      {
        "id": "chimL",
        "type": "platform",
        "x": 220,
        "y": 430,
        "w": 30,
        "h": 460
      },
      {
        "id": "chimR",
        "type": "platform",
        "x": 370,
        "y": 430,
        "w": 30,
        "h": 460
      },
      {
        "id": "shelf",
        "type": "platform",
        "x": 450,
        "y": 1030,
        "w": 200,
        "h": 26
      }
    ],
    "objects": [
      {
        "id": "rock",
        "type": "boulder",
        "x": 290,
        "y": 470,
        "radius": 26,
        "density": 0.03,
        "restitution": 0.06,
        "friction": 0.35,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-chimney-190057",
    "world": "backyard",
    "solver": null,
    "freezeAt": 510,
    "generated": {
      "archetype": "chimney",
      "seed": 190057
    }
  },
  {
    "verb": "BRIDGE",
    "hint": "GET HIM ACROSS",
    "milo": {
      "start": {
        "x": 70,
        "y": 890
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 660,
      "y": 970,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "bankL",
        "type": "platform",
        "x": 0,
        "y": 890,
        "w": 340,
        "h": 390
      },
      {
        "id": "bankR",
        "type": "platform",
        "x": 530,
        "y": 970,
        "w": 190,
        "h": 310
      }
    ],
    "objects": [],
    "zones": [
      {
        "id": "pit",
        "kind": "zone",
        "x": 345,
        "y": 1215,
        "w": 180,
        "h": 65,
        "lethal": true
      }
    ],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-crossing-1",
    "world": "backyard",
    "solver": null,
    "freezeAt": 900,
    "generated": {
      "archetype": "crossing",
      "seed": 1
    }
  },
  {
    "verb": "BLOCK",
    "hint": "IT WILL DROP ON HIM",
    "milo": {
      "start": {
        "x": 130,
        "y": 1160
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 660,
      "y": 1160,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1160,
        "w": 720,
        "h": 120
      },
      {
        "id": "shelfL",
        "type": "platform",
        "x": 190,
        "y": 750,
        "w": 100,
        "h": 28
      },
      {
        "id": "shelfR",
        "type": "platform",
        "x": 470,
        "y": 750,
        "w": 100,
        "h": 28
      }
    ],
    "objects": [
      {
        "id": "rock",
        "type": "boulder",
        "x": 380,
        "y": 320,
        "radius": 28,
        "density": 0.03,
        "restitution": 0.06,
        "friction": 0.4,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-drop-87110",
    "world": "backyard",
    "solver": null,
    "freezeAt": 610,
    "generated": {
      "archetype": "drop",
      "seed": 87110
    }
  },
  {
    "verb": "INTERCEPT",
    "hint": "STOP THE ROLLER",
    "milo": {
      "start": {
        "x": 70,
        "y": 1120
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 665,
      "y": 1120,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1120,
        "w": 720,
        "h": 160
      },
      {
        "id": "ledge",
        "type": "platform",
        "x": 540,
        "y": 850,
        "w": 180,
        "h": 30
      }
    ],
    "objects": [
      {
        "id": "roller",
        "type": "boulder",
        "x": 630,
        "y": 816,
        "radius": 34,
        "density": 0.04,
        "restitution": 0.05,
        "friction": 0.15,
        "frictionAir": 0,
        "vx": -340,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 500,
      "denyZones": []
    },
    "id": "gen-roller-245490",
    "world": "backyard",
    "solver": null,
    "freezeAt": 610,
    "generated": {
      "archetype": "roller",
      "seed": 245490
    }
  },
  {
    "verb": "TRIGGER",
    "hint": "THE PLATE OPENS THE GATE",
    "milo": {
      "start": {
        "x": 100,
        "y": 1120
      },
      "speed": 190
    },
    "goal": {
      "id": "goal",
      "x": 665,
      "y": 1120,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1120,
        "w": 720,
        "h": 160
      },
      {
        "id": "shelf",
        "type": "platform",
        "x": 290,
        "y": 900,
        "w": 190,
        "h": 26
      }
    ],
    "objects": [
      {
        "id": "plate",
        "type": "switch",
        "x": 310,
        "y": 868,
        "w": 130,
        "h": 32,
        "triggers": [
          "gate"
        ]
      },
      {
        "id": "gate",
        "type": "gate",
        "x": 560,
        "y": 980,
        "w": 34,
        "h": 140
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-trigger-95029",
    "world": "backyard",
    "solver": null,
    "freezeAt": 900,
    "generated": {
      "archetype": "trigger",
      "seed": 95029
    }
  },
  {
    "verb": "CHOOSE",
    "hint": "KEEP IT OFF HIM",
    "milo": {
      "start": {
        "x": 90,
        "y": 1152
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 660,
      "y": 1152,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1152,
        "w": 720,
        "h": 128
      },
      {
        "id": "chimL",
        "type": "platform",
        "x": 220,
        "y": 340,
        "w": 30,
        "h": 410
      },
      {
        "id": "chimR",
        "type": "platform",
        "x": 380,
        "y": 340,
        "w": 30,
        "h": 410
      },
      {
        "id": "shelf",
        "type": "platform",
        "x": 490,
        "y": 1020,
        "w": 200,
        "h": 26
      }
    ],
    "objects": [
      {
        "id": "rock",
        "type": "boulder",
        "x": 285,
        "y": 430,
        "radius": 26,
        "density": 0.03,
        "restitution": 0.06,
        "friction": 0.35,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-chimney-79191",
    "world": "backyard",
    "solver": null,
    "freezeAt": 540,
    "generated": {
      "archetype": "chimney",
      "seed": 79191
    }
  },
  {
    "verb": "BRIDGE",
    "hint": "GET HIM ACROSS",
    "milo": {
      "start": {
        "x": 110,
        "y": 910
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 670,
      "y": 1110,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "bankL",
        "type": "platform",
        "x": 0,
        "y": 910,
        "w": 360,
        "h": 370
      },
      {
        "id": "bankR",
        "type": "platform",
        "x": 590,
        "y": 1110,
        "w": 130,
        "h": 170
      }
    ],
    "objects": [],
    "zones": [
      {
        "id": "pit",
        "kind": "zone",
        "x": 365,
        "y": 1215,
        "w": 220,
        "h": 65,
        "lethal": true
      }
    ],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-crossing-15839",
    "world": "backyard",
    "solver": null,
    "freezeAt": 900,
    "generated": {
      "archetype": "crossing",
      "seed": 15839
    }
  },
  {
    "verb": "BLOCK",
    "hint": "IT WILL DROP ON HIM",
    "milo": {
      "start": {
        "x": 80,
        "y": 1120
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 600,
      "y": 1120,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1120,
        "w": 720,
        "h": 160
      },
      {
        "id": "shelfL",
        "type": "platform",
        "x": 100,
        "y": 800,
        "w": 120,
        "h": 28
      },
      {
        "id": "shelfR",
        "type": "platform",
        "x": 400,
        "y": 800,
        "w": 120,
        "h": 28
      }
    ],
    "objects": [
      {
        "id": "rock",
        "type": "boulder",
        "x": 310,
        "y": 310,
        "radius": 24,
        "density": 0.03,
        "restitution": 0.06,
        "friction": 0.4,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-drop-47515",
    "world": "backyard",
    "solver": null,
    "freezeAt": 590,
    "generated": {
      "archetype": "drop",
      "seed": 47515
    }
  },
  {
    "verb": "INTERCEPT",
    "hint": "STOP THE ROLLER",
    "milo": {
      "start": {
        "x": 110,
        "y": 1152
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 665,
      "y": 1152,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1152,
        "w": 720,
        "h": 128
      },
      {
        "id": "ledge",
        "type": "platform",
        "x": 480,
        "y": 860,
        "w": 240,
        "h": 30
      }
    ],
    "objects": [
      {
        "id": "roller",
        "type": "boulder",
        "x": 640,
        "y": 826,
        "radius": 34,
        "density": 0.04,
        "restitution": 0.05,
        "friction": 0.15,
        "frictionAir": 0,
        "vx": -360,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 560,
      "denyZones": []
    },
    "id": "gen-roller-190057",
    "world": "backyard",
    "solver": null,
    "freezeAt": 630,
    "generated": {
      "archetype": "roller",
      "seed": 190057
    }
  },
  {
    "verb": "CHOOSE",
    "hint": "KEEP IT OFF HIM",
    "milo": {
      "start": {
        "x": 80,
        "y": 1136
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 660,
      "y": 1136,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1136,
        "w": 720,
        "h": 144
      },
      {
        "id": "chimL",
        "type": "platform",
        "x": 200,
        "y": 380,
        "w": 30,
        "h": 460
      },
      {
        "id": "chimR",
        "type": "platform",
        "x": 370,
        "y": 380,
        "w": 30,
        "h": 460
      },
      {
        "id": "shelf",
        "type": "platform",
        "x": 500,
        "y": 1030,
        "w": 200,
        "h": 26
      }
    ],
    "objects": [
      {
        "id": "rock",
        "type": "boulder",
        "x": 280,
        "y": 440,
        "radius": 24,
        "density": 0.03,
        "restitution": 0.06,
        "friction": 0.35,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-chimney-158381",
    "world": "backyard",
    "solver": null,
    "freezeAt": 520,
    "generated": {
      "archetype": "chimney",
      "seed": 158381
    }
  },
  {
    "verb": "BRIDGE",
    "hint": "GET HIM ACROSS",
    "milo": {
      "start": {
        "x": 70,
        "y": 870
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 670,
      "y": 1030,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "bankL",
        "type": "platform",
        "x": 0,
        "y": 870,
        "w": 300,
        "h": 410
      },
      {
        "id": "bankR",
        "type": "platform",
        "x": 540,
        "y": 1030,
        "w": 180,
        "h": 250
      }
    ],
    "objects": [],
    "zones": [
      {
        "id": "pit",
        "kind": "zone",
        "x": 305,
        "y": 1215,
        "w": 230,
        "h": 65,
        "lethal": true
      }
    ],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-crossing-95029",
    "world": "backyard",
    "solver": null,
    "freezeAt": 900,
    "generated": {
      "archetype": "crossing",
      "seed": 95029
    }
  },
  {
    "verb": "BLOCK",
    "hint": "IT WILL DROP ON HIM",
    "milo": {
      "start": {
        "x": 150,
        "y": 1120
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 650,
      "y": 1120,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1120,
        "w": 720,
        "h": 160
      },
      {
        "id": "shelfL",
        "type": "platform",
        "x": 125,
        "y": 800,
        "w": 130,
        "h": 28
      },
      {
        "id": "shelfR",
        "type": "platform",
        "x": 445,
        "y": 800,
        "w": 130,
        "h": 28
      }
    ],
    "objects": [
      {
        "id": "rock",
        "type": "boulder",
        "x": 350,
        "y": 340,
        "radius": 30,
        "density": 0.03,
        "restitution": 0.06,
        "friction": 0.4,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-drop-166300",
    "world": "backyard",
    "solver": null,
    "freezeAt": 570,
    "generated": {
      "archetype": "drop",
      "seed": 166300
    }
  },
  {
    "verb": "CHOOSE",
    "hint": "KEEP IT OFF HIM",
    "milo": {
      "start": {
        "x": 60,
        "y": 1136
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 660,
      "y": 1136,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1136,
        "w": 720,
        "h": 144
      },
      {
        "id": "chimL",
        "type": "platform",
        "x": 210,
        "y": 390,
        "w": 30,
        "h": 410
      },
      {
        "id": "chimR",
        "type": "platform",
        "x": 390,
        "y": 390,
        "w": 30,
        "h": 410
      },
      {
        "id": "shelf",
        "type": "platform",
        "x": 460,
        "y": 1010,
        "w": 200,
        "h": 26
      }
    ],
    "objects": [
      {
        "id": "rock",
        "type": "boulder",
        "x": 285,
        "y": 440,
        "radius": 26,
        "density": 0.03,
        "restitution": 0.06,
        "friction": 0.35,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-chimney-47515",
    "world": "backyard",
    "solver": null,
    "freezeAt": 520,
    "generated": {
      "archetype": "chimney",
      "seed": 47515
    }
  },
  {
    "verb": "BRIDGE",
    "hint": "GET HIM ACROSS",
    "milo": {
      "start": {
        "x": 90,
        "y": 1000
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 630,
      "y": 1100,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "bankL",
        "type": "platform",
        "x": 0,
        "y": 1000,
        "w": 290,
        "h": 280
      },
      {
        "id": "bankR",
        "type": "platform",
        "x": 500,
        "y": 1100,
        "w": 220,
        "h": 180
      }
    ],
    "objects": [],
    "zones": [
      {
        "id": "pit",
        "kind": "zone",
        "x": 295,
        "y": 1215,
        "w": 200,
        "h": 65,
        "lethal": true
      }
    ],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-crossing-87110",
    "world": "backyard",
    "solver": null,
    "freezeAt": 900,
    "generated": {
      "archetype": "crossing",
      "seed": 87110
    }
  },
  {
    "verb": "BLOCK",
    "hint": "IT WILL DROP ON HIM",
    "milo": {
      "start": {
        "x": 110,
        "y": 1088
      },
      "speed": 220
    },
    "goal": {
      "id": "goal",
      "x": 620,
      "y": 1088,
      "w": 70,
      "h": 140
    },
    "static": [
      {
        "id": "ground",
        "type": "platform",
        "x": 0,
        "y": 1088,
        "w": 720,
        "h": 192
      },
      {
        "id": "shelfL",
        "type": "platform",
        "x": 95,
        "y": 870,
        "w": 130,
        "h": 28
      },
      {
        "id": "shelfR",
        "type": "platform",
        "x": 435,
        "y": 870,
        "w": 130,
        "h": 28
      }
    ],
    "objects": [
      {
        "id": "rock",
        "type": "boulder",
        "x": 330,
        "y": 330,
        "radius": 30,
        "density": 0.03,
        "restitution": 0.06,
        "friction": 0.4,
        "lethal": {
          "kind": "impact",
          "minSpeed": 400,
          "graceRadius": 6
        }
      }
    ],
    "zones": [],
    "drawing": {
      "maxLength": 900,
      "denyZones": []
    },
    "id": "gen-drop-134624",
    "world": "backyard",
    "solver": null,
    "freezeAt": 550,
    "generated": {
      "archetype": "drop",
      "seed": 134624
    }
  }
];

export const POOL_SOLVER = {
  "gen-chimney-174219": {
    "solvable": true,
    "solutionBreadth": 0.1075,
    "precisionFloor": 65,
    "worstJitter": 2,
    "distinctFamilies": 6,
    "twoStarLength": 300,
    "threeStarLength": 230,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-crossing-31677": {
    "solvable": true,
    "solutionBreadth": 0.0366,
    "precisionFloor": 65,
    "worstJitter": 0,
    "distinctFamilies": 6,
    "twoStarLength": 347,
    "threeStarLength": 288,
    "shortestWin": 165,
    "measuredAt": "2026-09-27"
  },
  "gen-drop-23758": {
    "solvable": true,
    "solutionBreadth": 0.1429,
    "precisionFloor": 65,
    "worstJitter": 2,
    "distinctFamilies": 6,
    "twoStarLength": 300,
    "threeStarLength": 230,
    "shortestWin": 100,
    "measuredAt": "2026-09-27"
  },
  "gen-roller-87110": {
    "solvable": true,
    "solutionBreadth": 0.1956,
    "precisionFloor": 65,
    "worstJitter": 2,
    "distinctFamilies": 6,
    "twoStarLength": 300,
    "threeStarLength": 184,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-trigger-7920": {
    "solvable": true,
    "solutionBreadth": 0.2356,
    "precisionFloor": 65,
    "worstJitter": 2,
    "distinctFamilies": 6,
    "twoStarLength": 288,
    "threeStarLength": 184,
    "shortestWin": 86,
    "measuredAt": "2026-09-27"
  },
  "gen-chimney-245490": {
    "solvable": true,
    "solutionBreadth": 0.1027,
    "precisionFloor": 65,
    "worstJitter": 1,
    "distinctFamilies": 6,
    "twoStarLength": 300,
    "threeStarLength": 230,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-crossing-174219": {
    "solvable": true,
    "solutionBreadth": 0.0602,
    "precisionFloor": 65,
    "worstJitter": 1,
    "distinctFamilies": 6,
    "twoStarLength": 315,
    "threeStarLength": 230,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-drop-39596": {
    "solvable": true,
    "solutionBreadth": 0.1451,
    "precisionFloor": 65,
    "worstJitter": 2,
    "distinctFamilies": 6,
    "twoStarLength": 300,
    "threeStarLength": 230,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-roller-182138": {
    "solvable": true,
    "solutionBreadth": 0.1658,
    "precisionFloor": 65,
    "worstJitter": 2,
    "distinctFamilies": 5,
    "twoStarLength": 288,
    "threeStarLength": 230,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-trigger-71272": {
    "solvable": true,
    "solutionBreadth": 0.1899,
    "precisionFloor": 65,
    "worstJitter": 1,
    "distinctFamilies": 5,
    "twoStarLength": 288,
    "threeStarLength": 184,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-chimney-197976": {
    "solvable": true,
    "solutionBreadth": 0.0979,
    "precisionFloor": 65,
    "worstJitter": 2,
    "distinctFamilies": 6,
    "twoStarLength": 300,
    "threeStarLength": 230,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-crossing-118786": {
    "solvable": true,
    "solutionBreadth": 0.0414,
    "precisionFloor": 65,
    "worstJitter": 0,
    "distinctFamilies": 5,
    "twoStarLength": 390,
    "threeStarLength": 242,
    "shortestWin": 165,
    "measuredAt": "2026-09-27"
  },
  "gen-drop-142543": {
    "solvable": true,
    "solutionBreadth": 0.142,
    "precisionFloor": 65,
    "worstJitter": 3,
    "distinctFamilies": 6,
    "twoStarLength": 300,
    "threeStarLength": 229,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-roller-158381": {
    "solvable": true,
    "solutionBreadth": 0.1854,
    "precisionFloor": 65,
    "worstJitter": 2,
    "distinctFamilies": 6,
    "twoStarLength": 288,
    "threeStarLength": 184,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-trigger-134624": {
    "solvable": true,
    "solutionBreadth": 0.1832,
    "precisionFloor": 65,
    "worstJitter": 2,
    "distinctFamilies": 6,
    "twoStarLength": 288,
    "threeStarLength": 165,
    "shortestWin": 94,
    "measuredAt": "2026-09-27"
  },
  "gen-chimney-166300": {
    "solvable": true,
    "solutionBreadth": 0.0988,
    "precisionFloor": 65,
    "worstJitter": 3,
    "distinctFamilies": 6,
    "twoStarLength": 300,
    "threeStarLength": 230,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-crossing-39596": {
    "solvable": true,
    "solutionBreadth": 0.0403,
    "precisionFloor": 65,
    "worstJitter": 0,
    "distinctFamilies": 4,
    "twoStarLength": 390,
    "threeStarLength": 288,
    "shortestWin": 165,
    "measuredAt": "2026-09-27"
  },
  "gen-drop-1": {
    "solvable": true,
    "solutionBreadth": 0.1306,
    "precisionFloor": 65,
    "worstJitter": 3,
    "distinctFamilies": 6,
    "twoStarLength": 300,
    "threeStarLength": 230,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-roller-229652": {
    "solvable": true,
    "solutionBreadth": 0.1782,
    "precisionFloor": 65,
    "worstJitter": 4,
    "distinctFamilies": 6,
    "twoStarLength": 288,
    "threeStarLength": 190,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-trigger-110867": {
    "solvable": true,
    "solutionBreadth": 0.1634,
    "precisionFloor": 65,
    "worstJitter": 2,
    "distinctFamilies": 6,
    "twoStarLength": 295,
    "threeStarLength": 165,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-chimney-63353": {
    "solvable": true,
    "solutionBreadth": 0.0875,
    "precisionFloor": 65,
    "worstJitter": 2,
    "distinctFamilies": 6,
    "twoStarLength": 300,
    "threeStarLength": 230,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-crossing-55434": {
    "solvable": true,
    "solutionBreadth": 0.0247,
    "precisionFloor": 45,
    "worstJitter": 0,
    "distinctFamilies": 4,
    "twoStarLength": 390,
    "threeStarLength": 284,
    "shortestWin": 230,
    "measuredAt": "2026-09-27"
  },
  "gen-drop-55434": {
    "solvable": true,
    "solutionBreadth": 0.129,
    "precisionFloor": 65,
    "worstJitter": 2,
    "distinctFamilies": 6,
    "twoStarLength": 300,
    "threeStarLength": 230,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-roller-110867": {
    "solvable": true,
    "solutionBreadth": 0.2044,
    "precisionFloor": 65,
    "worstJitter": 3,
    "distinctFamilies": 6,
    "twoStarLength": 288,
    "threeStarLength": 165,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-trigger-118786": {
    "solvable": true,
    "solutionBreadth": 0.158,
    "precisionFloor": 65,
    "worstJitter": 1,
    "distinctFamilies": 6,
    "twoStarLength": 288,
    "threeStarLength": 165,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-chimney-190057": {
    "solvable": true,
    "solutionBreadth": 0.1074,
    "precisionFloor": 65,
    "worstJitter": 1,
    "distinctFamilies": 6,
    "twoStarLength": 300,
    "threeStarLength": 230,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-crossing-1": {
    "solvable": true,
    "solutionBreadth": 0.0264,
    "precisionFloor": 45,
    "worstJitter": 0,
    "distinctFamilies": 5,
    "twoStarLength": 390,
    "threeStarLength": 230,
    "shortestWin": 165,
    "measuredAt": "2026-09-27"
  },
  "gen-drop-87110": {
    "solvable": true,
    "solutionBreadth": 0.1243,
    "precisionFloor": 65,
    "worstJitter": 2,
    "distinctFamilies": 6,
    "twoStarLength": 300,
    "threeStarLength": 230,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-roller-245490": {
    "solvable": true,
    "solutionBreadth": 0.1633,
    "precisionFloor": 65,
    "worstJitter": 2,
    "distinctFamilies": 5,
    "twoStarLength": 288,
    "threeStarLength": 165,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-trigger-95029": {
    "solvable": true,
    "solutionBreadth": 0.0367,
    "precisionFloor": 45,
    "worstJitter": 2,
    "distinctFamilies": 4,
    "twoStarLength": 300,
    "threeStarLength": 230,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-chimney-79191": {
    "solvable": true,
    "solutionBreadth": 0.0863,
    "precisionFloor": 65,
    "worstJitter": 1,
    "distinctFamilies": 6,
    "twoStarLength": 300,
    "threeStarLength": 230,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-crossing-15839": {
    "solvable": true,
    "solutionBreadth": 0.0293,
    "precisionFloor": 65,
    "worstJitter": 0,
    "distinctFamilies": 4,
    "twoStarLength": 390,
    "threeStarLength": 300,
    "shortestWin": 243,
    "measuredAt": "2026-09-27"
  },
  "gen-drop-47515": {
    "solvable": true,
    "solutionBreadth": 0.128,
    "precisionFloor": 65,
    "worstJitter": 2,
    "distinctFamilies": 6,
    "twoStarLength": 300,
    "threeStarLength": 230,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-roller-190057": {
    "solvable": true,
    "solutionBreadth": 0.1425,
    "precisionFloor": 65,
    "worstJitter": 3,
    "distinctFamilies": 5,
    "twoStarLength": 295,
    "threeStarLength": 230,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-chimney-158381": {
    "solvable": true,
    "solutionBreadth": 0.0986,
    "precisionFloor": 65,
    "worstJitter": 2,
    "distinctFamilies": 6,
    "twoStarLength": 300,
    "threeStarLength": 230,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-crossing-95029": {
    "solvable": true,
    "solutionBreadth": 0.0298,
    "precisionFloor": 45,
    "worstJitter": 0,
    "distinctFamilies": 4,
    "twoStarLength": 390,
    "threeStarLength": 288,
    "shortestWin": 230,
    "measuredAt": "2026-09-27"
  },
  "gen-drop-166300": {
    "solvable": true,
    "solutionBreadth": 0.1236,
    "precisionFloor": 65,
    "worstJitter": 3,
    "distinctFamilies": 6,
    "twoStarLength": 320,
    "threeStarLength": 230,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-chimney-47515": {
    "solvable": true,
    "solutionBreadth": 0.0947,
    "precisionFloor": 65,
    "worstJitter": 2,
    "distinctFamilies": 6,
    "twoStarLength": 300,
    "threeStarLength": 230,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  },
  "gen-crossing-87110": {
    "solvable": true,
    "solutionBreadth": 0.022,
    "precisionFloor": 45,
    "worstJitter": 0,
    "distinctFamilies": 4,
    "twoStarLength": 390,
    "threeStarLength": 300,
    "shortestWin": 243,
    "measuredAt": "2026-09-27"
  },
  "gen-drop-134624": {
    "solvable": true,
    "solutionBreadth": 0.1152,
    "precisionFloor": 65,
    "worstJitter": 2,
    "distinctFamilies": 6,
    "twoStarLength": 340,
    "threeStarLength": 230,
    "shortestWin": 110,
    "measuredAt": "2026-09-27"
  }
};

export const HELD_FROM_DAILY = {
  "a8-jam": "inside 165u of ink the only wins a hand can land are dropped lines, and it lands 32% of them (14/44) — under the 50% an unanchored solution needs",
  "a28-duct": "not one of 23 winning strokes inside 110u of ink survives a hand",
  "a43-crack": "not one of 5 winning strokes inside 110u of ink survives a hand"
};
