// GENERATED by tools/levelgen/bake.js — do not edit by hand.
//
// The certificate for every level the daily deals, campaign and pool: a
// stroke the sweep proved wins INSIDE THE DAILY BUDGET (`ink`) and that a
// shaky hand keeps winning, with the counts measured at that budget. Tools
// only — the game never imports this, so it costs the bundle nothing.

export const DAILY_SOLUTIONS = {
  "a1-wall": {
    "id": "a1-wall",
    "ink": 226,
    "winners": 56,
    "robust": 30,
    "anchoredRobust": 18,
    "handRate": 0.536,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 9,
      "anchors": 3,
      "points": [
        {
          "x": 378.8,
          "y": 654.6
        },
        {
          "x": 406.3,
          "y": 702.2
        },
        {
          "x": 433.8,
          "y": 749.8
        },
        {
          "x": 461.3,
          "y": 797.4
        }
      ]
    }
  },
  "a2-gap": {
    "id": "a2-gap",
    "ink": 253,
    "winners": 28,
    "robust": 13,
    "anchoredRobust": 13,
    "handRate": 0.464,
    "solution": {
      "family": "line",
      "length": 230,
      "parts": 11,
      "anchors": 8,
      "points": [
        {
          "x": 320.4,
          "y": 989.6
        },
        {
          "x": 386.8,
          "y": 1028
        },
        {
          "x": 453.2,
          "y": 1066.3
        },
        {
          "x": 519.6,
          "y": 1104.6
        }
      ]
    }
  },
  "a3-redirect": {
    "id": "a3-redirect",
    "ink": 230,
    "winners": 86,
    "robust": 29,
    "anchoredRobust": 15,
    "handRate": 0.337,
    "solution": {
      "family": "span",
      "length": 198,
      "parts": 12,
      "anchors": 8,
      "points": [
        {
          "x": 280,
          "y": 880
        },
        {
          "x": 300,
          "y": 860
        },
        {
          "x": 320,
          "y": 840
        },
        {
          "x": 340,
          "y": 820
        },
        {
          "x": 360,
          "y": 800
        },
        {
          "x": 380,
          "y": 780
        },
        {
          "x": 400,
          "y": 760
        },
        {
          "x": 420,
          "y": 740
        }
      ]
    }
  },
  "a4-catch": {
    "id": "a4-catch",
    "ink": 260,
    "winners": 13,
    "robust": 7,
    "anchoredRobust": 7,
    "handRate": 0.538,
    "solution": {
      "family": "line",
      "length": 230,
      "parts": 13,
      "anchors": 2,
      "points": [
        {
          "x": 185,
          "y": 995
        },
        {
          "x": 261.7,
          "y": 995
        },
        {
          "x": 338.3,
          "y": 995
        },
        {
          "x": 415,
          "y": 995
        }
      ]
    }
  },
  "a5-hang": {
    "id": "a5-hang",
    "ink": 230,
    "winners": 79,
    "robust": 39,
    "anchoredRobust": 20,
    "handRate": 0.494,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 9,
      "anchors": 6,
      "points": [
        {
          "x": 491.4,
          "y": 421.6
        },
        {
          "x": 443.8,
          "y": 449.1
        },
        {
          "x": 396.2,
          "y": 476.6
        },
        {
          "x": 348.6,
          "y": 504.1
        }
      ]
    }
  },
  "a9-chute": {
    "id": "a9-chute",
    "ink": 184,
    "winners": 126,
    "robust": 110,
    "anchoredRobust": 4,
    "handRate": 0.873,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 10,
      "anchors": 7,
      "points": [
        {
          "x": 228.6,
          "y": 634.8
        },
        {
          "x": 276.2,
          "y": 662.3
        },
        {
          "x": 323.8,
          "y": 689.8
        },
        {
          "x": 371.4,
          "y": 717.3
        }
      ]
    }
  },
  "a10-switch": {
    "id": "a10-switch",
    "ink": 192,
    "winners": 18,
    "robust": 6,
    "anchoredRobust": 6,
    "handRate": 0.333,
    "solution": {
      "family": "span",
      "length": 139,
      "parts": 8,
      "anchors": 7,
      "points": [
        {
          "x": 280,
          "y": 700
        },
        {
          "x": 294.3,
          "y": 701.6
        },
        {
          "x": 308.6,
          "y": 700.6
        },
        {
          "x": 322.9,
          "y": 695
        },
        {
          "x": 337.1,
          "y": 683.5
        },
        {
          "x": 351.4,
          "y": 666.3
        },
        {
          "x": 365.7,
          "y": 644.4
        },
        {
          "x": 380,
          "y": 620
        }
      ]
    }
  },
  "a11-deadweight": {
    "id": "a11-deadweight",
    "ink": 230,
    "winners": 16,
    "robust": 10,
    "anchoredRobust": 0,
    "handRate": 0.625,
    "solution": {
      "family": "line",
      "length": 110,
      "parts": 9,
      "anchors": 0,
      "points": [
        {
          "x": 467.6,
          "y": 690.8
        },
        {
          "x": 435.9,
          "y": 709.1
        },
        {
          "x": 404.1,
          "y": 727.5
        },
        {
          "x": 372.4,
          "y": 745.8
        }
      ]
    }
  },
  "a12-ontime": {
    "id": "a12-ontime",
    "ink": 183,
    "winners": 114,
    "robust": 62,
    "anchoredRobust": 21,
    "handRate": 0.544,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 10,
      "anchors": 1,
      "points": [
        {
          "x": 491.4,
          "y": 888.3
        },
        {
          "x": 443.8,
          "y": 915.8
        },
        {
          "x": 396.2,
          "y": 943.3
        },
        {
          "x": 348.6,
          "y": 970.8
        }
      ]
    }
  },
  "a13-yeet": {
    "id": "a13-yeet",
    "ink": 288,
    "winners": 14,
    "robust": 1,
    "anchoredRobust": 1,
    "handRate": 0.071,
    "solution": {
      "family": "line",
      "length": 230,
      "parts": 13,
      "anchors": 6,
      "points": [
        {
          "x": 200.4,
          "y": 676.1
        },
        {
          "x": 266.8,
          "y": 714.4
        },
        {
          "x": 333.2,
          "y": 752.7
        },
        {
          "x": 399.6,
          "y": 791.1
        }
      ]
    }
  },
  "a15-eitherway": {
    "id": "a15-eitherway",
    "ink": 184,
    "winners": 36,
    "robust": 25,
    "anchoredRobust": 9,
    "handRate": 0.694,
    "solution": {
      "family": "line",
      "length": 110,
      "parts": 9,
      "anchors": 6,
      "points": [
        {
          "x": 347.6,
          "y": 738.5
        },
        {
          "x": 315.9,
          "y": 756.8
        },
        {
          "x": 284.1,
          "y": 775.2
        },
        {
          "x": 252.4,
          "y": 793.5
        }
      ]
    }
  },
  "a19-updraft": {
    "id": "a19-updraft",
    "ink": 165,
    "winners": 26,
    "robust": 8,
    "anchoredRobust": 2,
    "handRate": 0.308,
    "solution": {
      "family": "line",
      "length": 110,
      "parts": 9,
      "anchors": 5,
      "points": [
        {
          "x": 180,
          "y": 783.6
        },
        {
          "x": 180,
          "y": 820.2
        },
        {
          "x": 180,
          "y": 856.9
        },
        {
          "x": 180,
          "y": 893.6
        }
      ]
    }
  },
  "a20-spring": {
    "id": "a20-spring",
    "ink": 165,
    "winners": 119,
    "robust": 33,
    "anchoredRobust": 4,
    "handRate": 0.277,
    "solution": {
      "family": "span",
      "length": 137,
      "parts": 8,
      "anchors": 8,
      "points": [
        {
          "x": 380,
          "y": 1152
        },
        {
          "x": 397.1,
          "y": 1165
        },
        {
          "x": 414.3,
          "y": 1175.5
        },
        {
          "x": 431.4,
          "y": 1181.2
        },
        {
          "x": 448.6,
          "y": 1181.2
        },
        {
          "x": 465.7,
          "y": 1175.5
        },
        {
          "x": 482.9,
          "y": 1165
        },
        {
          "x": 500,
          "y": 1152
        }
      ]
    }
  },
  "a21-lever": {
    "id": "a21-lever",
    "ink": 177,
    "winners": 33,
    "robust": 5,
    "anchoredRobust": 2,
    "handRate": 0.152,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 9,
      "anchors": 7,
      "points": [
        {
          "x": 251.4,
          "y": 684.8
        },
        {
          "x": 203.8,
          "y": 712.3
        },
        {
          "x": 156.2,
          "y": 739.8
        },
        {
          "x": 108.6,
          "y": 767.3
        }
      ]
    }
  },
  "a29-rail": {
    "id": "a29-rail",
    "ink": 230,
    "winners": 19,
    "robust": 7,
    "anchoredRobust": 7,
    "handRate": 0.368,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 11,
      "anchors": 8,
      "points": [
        {
          "x": 217.5,
          "y": 784.3
        },
        {
          "x": 272.5,
          "y": 784.3
        },
        {
          "x": 327.5,
          "y": 784.3
        },
        {
          "x": 382.5,
          "y": 784.3
        }
      ]
    }
  },
  "a30-float": {
    "id": "a30-float",
    "ink": 229,
    "winners": 8,
    "robust": 8,
    "anchoredRobust": 8,
    "handRate": 1,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 10,
      "anchors": 8,
      "points": [
        {
          "x": 251.4,
          "y": 594.2
        },
        {
          "x": 203.8,
          "y": 621.7
        },
        {
          "x": 156.2,
          "y": 649.2
        },
        {
          "x": 108.6,
          "y": 676.7
        }
      ]
    }
  },
  "a31-thorns": {
    "id": "a31-thorns",
    "ink": 165,
    "winners": 10,
    "robust": 2,
    "anchoredRobust": 2,
    "handRate": 0.2,
    "solution": {
      "family": "line",
      "length": 110,
      "parts": 9,
      "anchors": 7,
      "points": [
        {
          "x": 347.6,
          "y": 576.5
        },
        {
          "x": 315.9,
          "y": 594.8
        },
        {
          "x": 284.1,
          "y": 613.2
        },
        {
          "x": 252.4,
          "y": 631.5
        }
      ]
    }
  },
  "a34-sink": {
    "id": "a34-sink",
    "ink": 230,
    "winners": 9,
    "robust": 4,
    "anchoredRobust": 4,
    "handRate": 0.444,
    "solution": {
      "family": "span",
      "length": 166,
      "parts": 8,
      "anchors": 5,
      "points": [
        {
          "x": 300,
          "y": 820
        },
        {
          "x": 311.4,
          "y": 789.6
        },
        {
          "x": 322.9,
          "y": 765.3
        },
        {
          "x": 334.3,
          "y": 751.8
        },
        {
          "x": 345.7,
          "y": 751.8
        },
        {
          "x": 357.1,
          "y": 765.3
        },
        {
          "x": 368.6,
          "y": 789.6
        },
        {
          "x": 380,
          "y": 820
        }
      ]
    }
  },
  "gen-chimney-174219": {
    "id": "gen-chimney-174219",
    "ink": 230,
    "winners": 67,
    "robust": 28,
    "anchoredRobust": 14,
    "handRate": 0.418,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 10,
      "anchors": 8,
      "points": [
        {
          "x": 228.6,
          "y": 730.8
        },
        {
          "x": 276.2,
          "y": 758.3
        },
        {
          "x": 323.8,
          "y": 785.8
        },
        {
          "x": 371.4,
          "y": 813.3
        }
      ]
    }
  },
  "gen-crossing-31677": {
    "id": "gen-crossing-31677",
    "ink": 288,
    "winners": 23,
    "robust": 12,
    "anchoredRobust": 12,
    "handRate": 0.522,
    "solution": {
      "family": "line",
      "length": 230,
      "parts": 13,
      "anchors": 2,
      "points": [
        {
          "x": 305,
          "y": 984.3
        },
        {
          "x": 381.7,
          "y": 984.3
        },
        {
          "x": 458.3,
          "y": 984.3
        },
        {
          "x": 535,
          "y": 984.3
        }
      ]
    }
  },
  "gen-drop-23758": {
    "id": "gen-drop-23758",
    "ink": 230,
    "winners": 85,
    "robust": 43,
    "anchoredRobust": 26,
    "handRate": 0.506,
    "solution": {
      "family": "bowl",
      "length": 185,
      "parts": 9,
      "anchors": 7,
      "points": [
        {
          "x": 230,
          "y": 698
        },
        {
          "x": 247.5,
          "y": 722.1
        },
        {
          "x": 265,
          "y": 739.3
        },
        {
          "x": 282.5,
          "y": 749.6
        },
        {
          "x": 300,
          "y": 753
        },
        {
          "x": 317.5,
          "y": 749.6
        },
        {
          "x": 335,
          "y": 739.3
        },
        {
          "x": 352.5,
          "y": 722.1
        },
        {
          "x": 370,
          "y": 698
        }
      ]
    }
  },
  "gen-roller-87110": {
    "id": "gen-roller-87110",
    "ink": 184,
    "winners": 78,
    "robust": 41,
    "anchoredRobust": 8,
    "handRate": 0.526,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 10,
      "anchors": 8,
      "points": [
        {
          "x": 611.4,
          "y": 897.6
        },
        {
          "x": 563.8,
          "y": 925.1
        },
        {
          "x": 516.2,
          "y": 952.6
        },
        {
          "x": 468.6,
          "y": 980.1
        }
      ]
    }
  },
  "gen-trigger-7920": {
    "id": "gen-trigger-7920",
    "ink": 184,
    "winners": 104,
    "robust": 93,
    "anchoredRobust": 1,
    "handRate": 0.894,
    "solution": {
      "family": "span",
      "length": 137,
      "parts": 9,
      "anchors": 8,
      "points": [
        {
          "x": 180,
          "y": 640
        },
        {
          "x": 197.1,
          "y": 627
        },
        {
          "x": 214.3,
          "y": 616.5
        },
        {
          "x": 231.4,
          "y": 610.8
        },
        {
          "x": 248.6,
          "y": 610.8
        },
        {
          "x": 265.7,
          "y": 616.5
        },
        {
          "x": 282.9,
          "y": 627
        },
        {
          "x": 300,
          "y": 640
        }
      ]
    }
  },
  "gen-chimney-245490": {
    "id": "gen-chimney-245490",
    "ink": 230,
    "winners": 65,
    "robust": 28,
    "anchoredRobust": 11,
    "handRate": 0.431,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 9,
      "anchors": 5,
      "points": [
        {
          "x": 371.4,
          "y": 728.8
        },
        {
          "x": 323.8,
          "y": 756.3
        },
        {
          "x": 276.2,
          "y": 783.8
        },
        {
          "x": 228.6,
          "y": 811.3
        }
      ]
    }
  },
  "gen-crossing-174219": {
    "id": "gen-crossing-174219",
    "ink": 230,
    "winners": 20,
    "robust": 9,
    "anchoredRobust": 9,
    "handRate": 0.45,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 9,
      "anchors": 8,
      "points": [
        {
          "x": 348.6,
          "y": 1038.8
        },
        {
          "x": 396.2,
          "y": 1066.3
        },
        {
          "x": 443.8,
          "y": 1093.8
        },
        {
          "x": 491.4,
          "y": 1121.3
        }
      ]
    }
  },
  "gen-drop-39596": {
    "id": "gen-drop-39596",
    "ink": 230,
    "winners": 79,
    "robust": 40,
    "anchoredRobust": 10,
    "handRate": 0.506,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 9,
      "anchors": 3,
      "points": [
        {
          "x": 348.6,
          "y": 810
        },
        {
          "x": 396.2,
          "y": 837.5
        },
        {
          "x": 443.8,
          "y": 865
        },
        {
          "x": 491.4,
          "y": 892.5
        }
      ]
    }
  },
  "gen-roller-182138": {
    "id": "gen-roller-182138",
    "ink": 230,
    "winners": 100,
    "robust": 39,
    "anchoredRobust": 11,
    "handRate": 0.39,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 9,
      "anchors": 8,
      "points": [
        {
          "x": 348.6,
          "y": 858.2
        },
        {
          "x": 396.2,
          "y": 885.7
        },
        {
          "x": 443.8,
          "y": 913.2
        },
        {
          "x": 491.4,
          "y": 940.7
        }
      ]
    }
  },
  "gen-trigger-71272": {
    "id": "gen-trigger-71272",
    "ink": 184,
    "winners": 79,
    "robust": 78,
    "anchoredRobust": 0,
    "handRate": 0.987,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 9,
      "anchors": 0,
      "points": [
        {
          "x": 581.3,
          "y": 475
        },
        {
          "x": 553.8,
          "y": 522.6
        },
        {
          "x": 526.3,
          "y": 570.2
        },
        {
          "x": 498.8,
          "y": 617.9
        }
      ]
    }
  },
  "gen-chimney-197976": {
    "id": "gen-chimney-197976",
    "ink": 230,
    "winners": 63,
    "robust": 28,
    "anchoredRobust": 15,
    "handRate": 0.444,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 9,
      "anchors": 7,
      "points": [
        {
          "x": 371.4,
          "y": 708.8
        },
        {
          "x": 323.8,
          "y": 736.3
        },
        {
          "x": 276.2,
          "y": 763.8
        },
        {
          "x": 228.6,
          "y": 791.3
        }
      ]
    }
  },
  "gen-crossing-118786": {
    "id": "gen-crossing-118786",
    "ink": 242,
    "winners": 17,
    "robust": 6,
    "anchoredRobust": 6,
    "handRate": 0.353,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 10,
      "anchors": 3,
      "points": [
        {
          "x": 337.5,
          "y": 1045
        },
        {
          "x": 392.5,
          "y": 1045
        },
        {
          "x": 447.5,
          "y": 1045
        },
        {
          "x": 502.5,
          "y": 1045
        }
      ]
    }
  },
  "gen-drop-142543": {
    "id": "gen-drop-142543",
    "ink": 229,
    "winners": 60,
    "robust": 38,
    "anchoredRobust": 19,
    "handRate": 0.633,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 10,
      "anchors": 8,
      "points": [
        {
          "x": 337.5,
          "y": 718
        },
        {
          "x": 392.5,
          "y": 718
        },
        {
          "x": 447.5,
          "y": 718
        },
        {
          "x": 502.5,
          "y": 718
        }
      ]
    }
  },
  "gen-roller-158381": {
    "id": "gen-roller-158381",
    "ink": 184,
    "winners": 69,
    "robust": 26,
    "anchoredRobust": 11,
    "handRate": 0.377,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 9,
      "anchors": 1,
      "points": [
        {
          "x": 491.4,
          "y": 856.9
        },
        {
          "x": 443.8,
          "y": 884.4
        },
        {
          "x": 396.2,
          "y": 911.9
        },
        {
          "x": 348.6,
          "y": 939.4
        }
      ]
    }
  },
  "gen-trigger-134624": {
    "id": "gen-trigger-134624",
    "ink": 165,
    "winners": 81,
    "robust": 37,
    "anchoredRobust": 2,
    "handRate": 0.457,
    "solution": {
      "family": "span",
      "length": 154,
      "parts": 8,
      "anchors": 8,
      "points": [
        {
          "x": 170,
          "y": 630
        },
        {
          "x": 190,
          "y": 617
        },
        {
          "x": 210,
          "y": 606.5
        },
        {
          "x": 230,
          "y": 600.8
        },
        {
          "x": 250,
          "y": 600.8
        },
        {
          "x": 270,
          "y": 606.5
        },
        {
          "x": 290,
          "y": 617
        },
        {
          "x": 310,
          "y": 630
        }
      ]
    }
  },
  "gen-chimney-166300": {
    "id": "gen-chimney-166300",
    "ink": 230,
    "winners": 57,
    "robust": 26,
    "anchoredRobust": 11,
    "handRate": 0.456,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 10,
      "anchors": 8,
      "points": [
        {
          "x": 337.5,
          "y": 767
        },
        {
          "x": 392.5,
          "y": 767
        },
        {
          "x": 447.5,
          "y": 767
        },
        {
          "x": 502.5,
          "y": 767
        }
      ]
    }
  },
  "gen-crossing-39596": {
    "id": "gen-crossing-39596",
    "ink": 288,
    "winners": 23,
    "robust": 6,
    "anchoredRobust": 6,
    "handRate": 0.261,
    "solution": {
      "family": "line",
      "length": 230,
      "parts": 10,
      "anchors": 3,
      "points": [
        {
          "x": 305,
          "y": 1003.6
        },
        {
          "x": 381.7,
          "y": 1003.6
        },
        {
          "x": 458.3,
          "y": 1003.6
        },
        {
          "x": 535,
          "y": 1003.6
        }
      ]
    }
  },
  "gen-drop-1": {
    "id": "gen-drop-1",
    "ink": 230,
    "winners": 84,
    "robust": 33,
    "anchoredRobust": 19,
    "handRate": 0.393,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 9,
      "anchors": 8,
      "points": [
        {
          "x": 378.8,
          "y": 750.6
        },
        {
          "x": 406.3,
          "y": 798.2
        },
        {
          "x": 433.8,
          "y": 845.8
        },
        {
          "x": 461.3,
          "y": 893.4
        }
      ]
    }
  },
  "gen-roller-229652": {
    "id": "gen-roller-229652",
    "ink": 190,
    "winners": 72,
    "robust": 24,
    "anchoredRobust": 10,
    "handRate": 0.333,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 10,
      "anchors": 6,
      "points": [
        {
          "x": 337.5,
          "y": 928.1
        },
        {
          "x": 392.5,
          "y": 928.1
        },
        {
          "x": 447.5,
          "y": 928.1
        },
        {
          "x": 502.5,
          "y": 928.1
        }
      ]
    }
  },
  "gen-trigger-110867": {
    "id": "gen-trigger-110867",
    "ink": 165,
    "winners": 72,
    "robust": 36,
    "anchoredRobust": 0,
    "handRate": 0.5,
    "solution": {
      "family": "line",
      "length": 110,
      "parts": 9,
      "anchors": 0,
      "points": [
        {
          "x": 372.4,
          "y": 217.4
        },
        {
          "x": 404.1,
          "y": 235.7
        },
        {
          "x": 435.9,
          "y": 254
        },
        {
          "x": 467.6,
          "y": 272.4
        }
      ]
    }
  },
  "gen-chimney-63353": {
    "id": "gen-chimney-63353",
    "ink": 230,
    "winners": 54,
    "robust": 25,
    "anchoredRobust": 13,
    "handRate": 0.463,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 9,
      "anchors": 5,
      "points": [
        {
          "x": 371.4,
          "y": 740.8
        },
        {
          "x": 323.8,
          "y": 768.3
        },
        {
          "x": 276.2,
          "y": 795.8
        },
        {
          "x": 228.6,
          "y": 823.3
        }
      ]
    }
  },
  "gen-crossing-55434": {
    "id": "gen-crossing-55434",
    "ink": 284,
    "winners": 12,
    "robust": 5,
    "anchoredRobust": 5,
    "handRate": 0.417,
    "solution": {
      "family": "span",
      "length": 244,
      "parts": 12,
      "anchors": 6,
      "points": [
        {
          "x": 330,
          "y": 960
        },
        {
          "x": 362.9,
          "y": 971.4
        },
        {
          "x": 395.7,
          "y": 982.9
        },
        {
          "x": 428.6,
          "y": 994.3
        },
        {
          "x": 461.4,
          "y": 1005.7
        },
        {
          "x": 494.3,
          "y": 1017.1
        },
        {
          "x": 527.1,
          "y": 1028.6
        },
        {
          "x": 560,
          "y": 1040
        }
      ]
    }
  },
  "gen-drop-55434": {
    "id": "gen-drop-55434",
    "ink": 230,
    "winners": 68,
    "robust": 29,
    "anchoredRobust": 10,
    "handRate": 0.426,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 10,
      "anchors": 8,
      "points": [
        {
          "x": 491.4,
          "y": 820.3
        },
        {
          "x": 443.8,
          "y": 847.8
        },
        {
          "x": 396.2,
          "y": 875.3
        },
        {
          "x": 348.6,
          "y": 902.8
        }
      ]
    }
  },
  "gen-roller-110867": {
    "id": "gen-roller-110867",
    "ink": 165,
    "winners": 81,
    "robust": 23,
    "anchoredRobust": 3,
    "handRate": 0.284,
    "solution": {
      "family": "line",
      "length": 110,
      "parts": 9,
      "anchors": 2,
      "points": [
        {
          "x": 365,
          "y": 908.9
        },
        {
          "x": 401.7,
          "y": 908.9
        },
        {
          "x": 438.3,
          "y": 908.9
        },
        {
          "x": 475,
          "y": 908.9
        }
      ]
    }
  },
  "gen-trigger-118786": {
    "id": "gen-trigger-118786",
    "ink": 165,
    "winners": 72,
    "robust": 30,
    "anchoredRobust": 1,
    "handRate": 0.417,
    "solution": {
      "family": "line",
      "length": 110,
      "parts": 9,
      "anchors": 8,
      "points": [
        {
          "x": 467.6,
          "y": 816.2
        },
        {
          "x": 435.9,
          "y": 834.5
        },
        {
          "x": 404.1,
          "y": 852.9
        },
        {
          "x": 372.4,
          "y": 871.2
        }
      ]
    }
  },
  "gen-chimney-190057": {
    "id": "gen-chimney-190057",
    "ink": 230,
    "winners": 55,
    "robust": 24,
    "anchoredRobust": 13,
    "handRate": 0.436,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 9,
      "anchors": 8,
      "points": [
        {
          "x": 371.4,
          "y": 749.8
        },
        {
          "x": 323.8,
          "y": 777.3
        },
        {
          "x": 276.2,
          "y": 804.8
        },
        {
          "x": 228.6,
          "y": 832.3
        }
      ]
    }
  },
  "gen-crossing-1": {
    "id": "gen-crossing-1",
    "ink": 230,
    "winners": 8,
    "robust": 4,
    "anchoredRobust": 4,
    "handRate": 0.5,
    "solution": {
      "family": "span",
      "length": 215,
      "parts": 12,
      "anchors": 5,
      "points": [
        {
          "x": 340,
          "y": 890
        },
        {
          "x": 367.1,
          "y": 888.4
        },
        {
          "x": 394.3,
          "y": 889.4
        },
        {
          "x": 421.4,
          "y": 895
        },
        {
          "x": 448.6,
          "y": 906.5
        },
        {
          "x": 475.7,
          "y": 923.7
        },
        {
          "x": 502.9,
          "y": 945.6
        },
        {
          "x": 530,
          "y": 970
        }
      ]
    }
  },
  "gen-drop-87110": {
    "id": "gen-drop-87110",
    "ink": 230,
    "winners": 64,
    "robust": 24,
    "anchoredRobust": 8,
    "handRate": 0.375,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 10,
      "anchors": 6,
      "points": [
        {
          "x": 337.5,
          "y": 740
        },
        {
          "x": 392.5,
          "y": 740
        },
        {
          "x": 447.5,
          "y": 740
        },
        {
          "x": 502.5,
          "y": 740
        }
      ]
    }
  },
  "gen-roller-245490": {
    "id": "gen-roller-245490",
    "ink": 165,
    "winners": 66,
    "robust": 22,
    "anchoredRobust": 1,
    "handRate": 0.333,
    "solution": {
      "family": "line",
      "length": 110,
      "parts": 9,
      "anchors": 8,
      "points": [
        {
          "x": 245,
          "y": 1106.3
        },
        {
          "x": 281.7,
          "y": 1106.3
        },
        {
          "x": 318.3,
          "y": 1106.3
        },
        {
          "x": 355,
          "y": 1106.3
        }
      ]
    }
  },
  "gen-trigger-95029": {
    "id": "gen-trigger-95029",
    "ink": 230,
    "winners": 21,
    "robust": 14,
    "anchoredRobust": 0,
    "handRate": 0.667,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 9,
      "anchors": 0,
      "points": [
        {
          "x": 217.5,
          "y": 808.9
        },
        {
          "x": 272.5,
          "y": 808.9
        },
        {
          "x": 327.5,
          "y": 808.9
        },
        {
          "x": 382.5,
          "y": 808.9
        }
      ]
    }
  },
  "gen-chimney-79191": {
    "id": "gen-chimney-79191",
    "ink": 230,
    "winners": 55,
    "robust": 23,
    "anchoredRobust": 8,
    "handRate": 0.418,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 10,
      "anchors": 8,
      "points": [
        {
          "x": 217.5,
          "y": 746
        },
        {
          "x": 272.5,
          "y": 746
        },
        {
          "x": 327.5,
          "y": 746
        },
        {
          "x": 382.5,
          "y": 746
        }
      ]
    }
  },
  "gen-crossing-15839": {
    "id": "gen-crossing-15839",
    "ink": 300,
    "winners": 17,
    "robust": 4,
    "anchoredRobust": 4,
    "handRate": 0.235,
    "solution": {
      "family": "arc",
      "length": 288,
      "parts": 12,
      "anchors": 8,
      "points": [
        {
          "x": 290,
          "y": 1050
        },
        {
          "x": 333.3,
          "y": 1019.4
        },
        {
          "x": 376.7,
          "y": 1001.1
        },
        {
          "x": 420,
          "y": 995
        },
        {
          "x": 463.3,
          "y": 1001.1
        },
        {
          "x": 506.7,
          "y": 1019.4
        },
        {
          "x": 550,
          "y": 1050
        }
      ]
    }
  },
  "gen-drop-47515": {
    "id": "gen-drop-47515",
    "ink": 230,
    "winners": 64,
    "robust": 22,
    "anchoredRobust": 3,
    "handRate": 0.344,
    "solution": {
      "family": "span",
      "length": 192,
      "parts": 12,
      "anchors": 6,
      "points": [
        {
          "x": 220,
          "y": 800
        },
        {
          "x": 245.7,
          "y": 787
        },
        {
          "x": 271.4,
          "y": 776.5
        },
        {
          "x": 297.1,
          "y": 770.8
        },
        {
          "x": 322.9,
          "y": 770.8
        },
        {
          "x": 348.6,
          "y": 776.5
        },
        {
          "x": 374.3,
          "y": 787
        },
        {
          "x": 400,
          "y": 800
        }
      ]
    }
  },
  "gen-roller-190057": {
    "id": "gen-roller-190057",
    "ink": 230,
    "winners": 72,
    "robust": 20,
    "anchoredRobust": 7,
    "handRate": 0.278,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 9,
      "anchors": 4,
      "points": [
        {
          "x": 491.4,
          "y": 875.5
        },
        {
          "x": 443.8,
          "y": 903
        },
        {
          "x": 396.2,
          "y": 930.5
        },
        {
          "x": 348.6,
          "y": 958
        }
      ]
    }
  },
  "gen-chimney-158381": {
    "id": "gen-chimney-158381",
    "ink": 230,
    "winners": 52,
    "robust": 21,
    "anchoredRobust": 7,
    "handRate": 0.404,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 9,
      "anchors": 1,
      "points": [
        {
          "x": 228.6,
          "y": 850.5
        },
        {
          "x": 276.2,
          "y": 878
        },
        {
          "x": 323.8,
          "y": 905.5
        },
        {
          "x": 371.4,
          "y": 933
        }
      ]
    }
  },
  "gen-crossing-95029": {
    "id": "gen-crossing-95029",
    "ink": 288,
    "winners": 13,
    "robust": 3,
    "anchoredRobust": 3,
    "handRate": 0.231,
    "solution": {
      "family": "line",
      "length": 230,
      "parts": 10,
      "anchors": 2,
      "points": [
        {
          "x": 305,
          "y": 958.6
        },
        {
          "x": 381.7,
          "y": 958.6
        },
        {
          "x": 458.3,
          "y": 958.6
        },
        {
          "x": 535,
          "y": 958.6
        }
      ]
    }
  },
  "gen-drop-166300": {
    "id": "gen-drop-166300",
    "ink": 230,
    "winners": 63,
    "robust": 20,
    "anchoredRobust": 9,
    "handRate": 0.317,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 9,
      "anchors": 5,
      "points": [
        {
          "x": 491.4,
          "y": 825.9
        },
        {
          "x": 443.8,
          "y": 853.4
        },
        {
          "x": 396.2,
          "y": 880.9
        },
        {
          "x": 348.6,
          "y": 908.4
        }
      ]
    }
  },
  "gen-chimney-47515": {
    "id": "gen-chimney-47515",
    "ink": 230,
    "winners": 50,
    "robust": 21,
    "anchoredRobust": 11,
    "handRate": 0.42,
    "solution": {
      "family": "line",
      "length": 165,
      "parts": 10,
      "anchors": 8,
      "points": [
        {
          "x": 217.5,
          "y": 763
        },
        {
          "x": 272.5,
          "y": 763
        },
        {
          "x": 327.5,
          "y": 763
        },
        {
          "x": 382.5,
          "y": 763
        }
      ]
    }
  },
  "gen-crossing-87110": {
    "id": "gen-crossing-87110",
    "ink": 300,
    "winners": 14,
    "robust": 2,
    "anchoredRobust": 2,
    "handRate": 0.143,
    "solution": {
      "family": "arc",
      "length": 288,
      "parts": 11,
      "anchors": 8,
      "points": [
        {
          "x": 307.4,
          "y": 1010
        },
        {
          "x": 360.2,
          "y": 1005.2
        },
        {
          "x": 406.9,
          "y": 1011
        },
        {
          "x": 447.5,
          "y": 1027.4
        },
        {
          "x": 482,
          "y": 1054.3
        },
        {
          "x": 510.3,
          "y": 1091.9
        },
        {
          "x": 532.6,
          "y": 1140
        }
      ]
    }
  },
  "gen-drop-134624": {
    "id": "gen-drop-134624",
    "ink": 230,
    "winners": 47,
    "robust": 13,
    "anchoredRobust": 4,
    "handRate": 0.277,
    "solution": {
      "family": "bowl",
      "length": 185,
      "parts": 9,
      "anchors": 8,
      "points": [
        {
          "x": 350,
          "y": 843
        },
        {
          "x": 367.5,
          "y": 867.1
        },
        {
          "x": 385,
          "y": 884.3
        },
        {
          "x": 402.5,
          "y": 894.6
        },
        {
          "x": 420,
          "y": 898
        },
        {
          "x": 437.5,
          "y": 894.6
        },
        {
          "x": 455,
          "y": 884.3
        },
        {
          "x": 472.5,
          "y": 867.1
        },
        {
          "x": 490,
          "y": 843
        }
      ]
    }
  }
};
