// Star rating — Bible §4.3.
//
// Thresholds come from js/solverData.js, which is GENERATED by measuring the
// actual distribution of winning stroke lengths across the plausible stroke
// space. The source documents printed `twoStarLength: 620` as though it were
// data; it was invented, and no amount of care in the rest of the design
// survives a mastery system built on made-up numbers.
//
// Length is the only rating axis in V1 and that is deliberate: time is mostly
// determined by the level rather than the player, and "elegance" cannot be
// measured, only argued about. Length is honest, legible, and measurable.

import { SOLVER } from './solverData.js';
import { LINE } from './constants.js';

export function starsFor(levelId, strokeLength) {
  const s = SOLVER[levelId];
  if (!s || !strokeLength) return 1;
  if (strokeLength <= s.threeStarLength) return 3;
  if (strokeLength <= s.twoStarLength) return 2;
  return 1;
}

export function thresholds(levelId) {
  const s = SOLVER[levelId];
  return {
    two: s?.twoStarLength ?? LINE.maxLengthDefault,
    three: s?.threeStarLength ?? LINE.maxLengthDefault * 0.6,
  };
}

export const STAR_NAME = ['', 'RESCUED', 'CLEAN', 'COOKED NO MORE'];
