// GENERATED by tools/solver/representative.js — do not edit by hand.
//
// One stroke per level that wins AND keeps winning when drawn by a shaky
// hand. This is what the filmstrip films, so the filmstrips show the game
// being WON rather than an arbitrary stroke that mostly loses.

export const SOLUTIONS = {
  "a1-wall": {
    "id": "a1-wall",
    "winners": 279,
    "robust": 188,
    "anchoredRobust": 133,
    "handRate": 0.674,
    "solution": {
      "family": "arc",
      "length": 288,
      "parts": 11,
      "anchors": 8,
      "points": [
        {
          "x": 485,
          "y": 760.8
        },
        {
          "x": 489.8,
          "y": 813.7
        },
        {
          "x": 484,
          "y": 860.3
        },
        {
          "x": 467.6,
          "y": 900.9
        },
        {
          "x": 440.7,
          "y": 935.4
        },
        {
          "x": 403.1,
          "y": 963.8
        },
        {
          "x": 355,
          "y": 986
        }
      ]
    }
  },
  "a2-gap": {
    "id": "a2-gap",
    "winners": 139,
    "robust": 68,
    "anchoredRobust": 68,
    "handRate": 0.489,
    "solution": {
      "family": "arc",
      "length": 288,
      "parts": 12,
      "anchors": 8,
      "points": [
        {
          "x": 307.4,
          "y": 1039.3
        },
        {
          "x": 360.2,
          "y": 1034.5
        },
        {
          "x": 406.9,
          "y": 1040.3
        },
        {
          "x": 447.5,
          "y": 1056.7
        },
        {
          "x": 482,
          "y": 1083.6
        },
        {
          "x": 510.3,
          "y": 1121.2
        },
        {
          "x": 532.6,
          "y": 1169.3
        }
      ]
    }
  },
  "a3-redirect": {
    "id": "a3-redirect",
    "winners": 351,
    "robust": 210,
    "anchoredRobust": 129,
    "handRate": 0.598,
    "solution": {
      "family": "arc",
      "length": 288,
      "parts": 11,
      "anchors": 6,
      "points": [
        {
          "x": 307.4,
          "y": 765.6
        },
        {
          "x": 360.2,
          "y": 760.8
        },
        {
          "x": 406.9,
          "y": 766.6
        },
        {
          "x": 447.5,
          "y": 782.9
        },
        {
          "x": 482,
          "y": 809.9
        },
        {
          "x": 510.3,
          "y": 847.4
        },
        {
          "x": 532.6,
          "y": 895.6
        }
      ]
    }
  },
  "a4-catch": {
    "id": "a4-catch",
    "winners": 59,
    "robust": 35,
    "anchoredRobust": 35,
    "handRate": 0.593,
    "solution": {
      "family": "line",
      "length": 300,
      "parts": 11,
      "anchors": 8,
      "points": [
        {
          "x": 290.1,
          "y": 920
        },
        {
          "x": 376.7,
          "y": 970
        },
        {
          "x": 463.3,
          "y": 1020
        },
        {
          "x": 549.9,
          "y": 1070
        }
      ]
    }
  },
  "a5-hang": {
    "id": "a5-hang",
    "winners": 312,
    "robust": 221,
    "anchoredRobust": 164,
    "handRate": 0.708,
    "solution": {
      "family": "arc",
      "length": 288,
      "parts": 11,
      "anchors": 8,
      "points": [
        {
          "x": 307.4,
          "y": 571
        },
        {
          "x": 329.7,
          "y": 619.1
        },
        {
          "x": 358,
          "y": 656.7
        },
        {
          "x": 392.5,
          "y": 683.6
        },
        {
          "x": 433.1,
          "y": 700
        },
        {
          "x": 479.8,
          "y": 705.8
        },
        {
          "x": 532.6,
          "y": 701
        }
      ]
    }
  },
  "a7-prop": {
    "id": "a7-prop",
    "winners": 55,
    "robust": 12,
    "anchoredRobust": 12,
    "handRate": 0.218,
    "solution": {
      "family": "span",
      "length": 278,
      "parts": 11,
      "anchors": 6,
      "points": [
        {
          "x": 250,
          "y": 900
        },
        {
          "x": 288.6,
          "y": 913
        },
        {
          "x": 327.1,
          "y": 923.5
        },
        {
          "x": 365.7,
          "y": 929.2
        },
        {
          "x": 404.3,
          "y": 929.2
        },
        {
          "x": 442.9,
          "y": 923.5
        },
        {
          "x": 481.4,
          "y": 913
        },
        {
          "x": 520,
          "y": 900
        }
      ]
    }
  },
  "a8-jam": {
    "id": "a8-jam",
    "winners": 163,
    "robust": 89,
    "anchoredRobust": 16,
    "handRate": 0.546,
    "solution": {
      "family": "arc",
      "length": 288,
      "parts": 13,
      "anchors": 8,
      "points": [
        {
          "x": 412.6,
          "y": 1150.4
        },
        {
          "x": 359.8,
          "y": 1145.6
        },
        {
          "x": 313.1,
          "y": 1151.4
        },
        {
          "x": 272.5,
          "y": 1167.8
        },
        {
          "x": 238,
          "y": 1194.8
        },
        {
          "x": 209.7,
          "y": 1232.3
        },
        {
          "x": 187.4,
          "y": 1280.4
        }
      ]
    }
  },
  "a9-chute": {
    "id": "a9-chute",
    "winners": 668,
    "robust": 596,
    "anchoredRobust": 11,
    "handRate": 0.892,
    "solution": {
      "family": "line",
      "length": 230,
      "parts": 13,
      "anchors": 8,
      "points": [
        {
          "x": 200.4,
          "y": 618.5
        },
        {
          "x": 266.8,
          "y": 656.8
        },
        {
          "x": 333.2,
          "y": 695.2
        },
        {
          "x": 399.6,
          "y": 733.5
        }
      ]
    }
  },
  "a10-switch": {
    "id": "a10-switch",
    "winners": 94,
    "robust": 56,
    "anchoredRobust": 51,
    "handRate": 0.596,
    "solution": {
      "family": "span",
      "length": 284,
      "parts": 11,
      "anchors": 8,
      "points": [
        {
          "x": 215,
          "y": 700
        },
        {
          "x": 247.9,
          "y": 718.9
        },
        {
          "x": 280.7,
          "y": 731.9
        },
        {
          "x": 313.6,
          "y": 734
        },
        {
          "x": 346.4,
          "y": 722.5
        },
        {
          "x": 379.3,
          "y": 697.6
        },
        {
          "x": 412.1,
          "y": 661.8
        },
        {
          "x": 445,
          "y": 620
        }
      ]
    }
  }
};
