// GENERATED by tools/solver — do not edit by hand.
//
// Star thresholds here are MEASURED percentiles of winning stroke lengths
// across the plausible stroke space, not guesses. Re-run after any physics
// change: `node tools/solver`.

export const SOLVER = {
  "a1-wall": {
    "solvable": true,
    "solutionBreadth": 0.1268,
    "precisionFloor": 65,
    "worstJitter": 3,
    "distinctFamilies": 6,
    "twoStarLength": 300,
    "threeStarLength": 226,
    "shortestWin": 110,
    "measuredAt": "2026-09-14"
  },
  "a2-gap": {
    "solvable": true,
    "solutionBreadth": 0.0743,
    "precisionFloor": 65,
    "worstJitter": 2,
    "distinctFamilies": 6,
    "twoStarLength": 300,
    "threeStarLength": 253,
    "shortestWin": 165,
    "measuredAt": "2026-09-14"
  },
  "a3-redirect": {
    "solvable": true,
    "solutionBreadth": 0.1588,
    "precisionFloor": 65,
    "worstJitter": 2,
    "distinctFamilies": 6,
    "twoStarLength": 300,
    "threeStarLength": 230,
    "shortestWin": 110,
    "measuredAt": "2026-09-14"
  },
  "a4-catch": {
    "solvable": true,
    "solutionBreadth": 0.0303,
    "precisionFloor": 65,
    "worstJitter": 0,
    "distinctFamilies": 6,
    "twoStarLength": 367,
    "threeStarLength": 260,
    "shortestWin": 165,
    "measuredAt": "2026-09-14"
  },
  "a5-hang": {
    "solvable": true,
    "solutionBreadth": 0.1479,
    "precisionFloor": 65,
    "worstJitter": 3,
    "distinctFamilies": 5,
    "twoStarLength": 300,
    "threeStarLength": 230,
    "shortestWin": 110,
    "measuredAt": "2026-09-14"
  },
  "a7-prop": {
    "solvable": true,
    "solutionBreadth": 0.0279,
    "precisionFloor": 45,
    "worstJitter": 0,
    "distinctFamilies": 4,
    "twoStarLength": 390,
    "threeStarLength": 230,
    "shortestWin": 110,
    "measuredAt": "2026-09-14"
  },
  "a8-jam": {
    "solvable": true,
    "solutionBreadth": 0.0855,
    "precisionFloor": 65,
    "worstJitter": 2,
    "distinctFamilies": 5,
    "twoStarLength": 288,
    "threeStarLength": 165,
    "shortestWin": 110,
    "measuredAt": "2026-09-14"
  },
  "a9-chute": {
    "solvable": true,
    "solutionBreadth": 0.2964,
    "precisionFloor": 65,
    "worstJitter": 3,
    "distinctFamilies": 6,
    "twoStarLength": 288,
    "threeStarLength": 184,
    "shortestWin": 86,
    "measuredAt": "2026-09-14"
  },
  "a10-switch": {
    "solvable": true,
    "solutionBreadth": 0.0422,
    "precisionFloor": 65,
    "worstJitter": 1,
    "distinctFamilies": 5,
    "twoStarLength": 288,
    "threeStarLength": 192,
    "shortestWin": 110,
    "measuredAt": "2026-09-14"
  },
  "a11-deadweight": {
    "solvable": true,
    "solutionBreadth": 0.031,
    "precisionFloor": 65,
    "worstJitter": 1,
    "distinctFamilies": 4,
    "twoStarLength": 288,
    "threeStarLength": 230,
    "shortestWin": 110,
    "measuredAt": "2026-09-14"
  },
  "a12-ontime": {
    "solvable": true,
    "solutionBreadth": 0.2891,
    "precisionFloor": 65,
    "worstJitter": 2,
    "distinctFamilies": 6,
    "twoStarLength": 288,
    "threeStarLength": 183,
    "shortestWin": 110,
    "measuredAt": "2026-09-14"
  },
  "a13-yeet": {
    "solvable": true,
    "solutionBreadth": 0.0307,
    "precisionFloor": 65,
    "worstJitter": 0,
    "distinctFamilies": 4,
    "twoStarLength": 390,
    "threeStarLength": 288,
    "shortestWin": 230,
    "measuredAt": "2026-09-14"
  },
  "a14-twojobs": {
    "solvable": true,
    "solutionBreadth": 0.0419,
    "precisionFloor": 65,
    "worstJitter": 2,
    "distinctFamilies": 5,
    "twoStarLength": 295,
    "threeStarLength": 165,
    "shortestWin": 110,
    "measuredAt": "2026-09-14"
  },
  "a15-eitherway": {
    "solvable": true,
    "solutionBreadth": 0.0828,
    "precisionFloor": 65,
    "worstJitter": 3,
    "distinctFamilies": 6,
    "twoStarLength": 300,
    "threeStarLength": 184,
    "shortestWin": 110,
    "measuredAt": "2026-09-14"
  }
};
