// GENERATED by tools/solver — do not edit by hand.
//
// Star thresholds here are MEASURED percentiles of winning stroke lengths
// across the plausible stroke space, not guesses. Re-run after any physics
// change: `node tools/solver`.

export const SOLVER = {
  "a1-wall": {
    "solvable": true,
    "solutionBreadth": 0.2163,
    "precisionFloor": 65,
    "worstJitter": 1,
    "distinctFamilies": 6,
    "twoStarLength": 301,
    "threeStarLength": 222,
    "shortestWin": 110,
    "measuredAt": "2026-09-13"
  },
  "a2-gap": {
    "solvable": true,
    "solutionBreadth": 0.039,
    "precisionFloor": 45,
    "worstJitter": 0,
    "distinctFamilies": 2,
    "twoStarLength": 500,
    "threeStarLength": 300,
    "shortestWin": 200,
    "measuredAt": "2026-09-13"
  },
  "a3-redirect": {
    "solvable": true,
    "solutionBreadth": 0.2288,
    "precisionFloor": 65,
    "worstJitter": 3,
    "distinctFamilies": 6,
    "twoStarLength": 294,
    "threeStarLength": 228,
    "shortestWin": 110,
    "measuredAt": "2026-09-13"
  },
  "a4-catch": {
    "solvable": true,
    "solutionBreadth": 0.0747,
    "precisionFloor": 65,
    "worstJitter": 0,
    "distinctFamilies": 4,
    "twoStarLength": 390,
    "threeStarLength": 243,
    "shortestWin": 110,
    "measuredAt": "2026-09-13"
  },
  "a5-hang": {
    "solvable": true,
    "solutionBreadth": 0.1306,
    "precisionFloor": 65,
    "worstJitter": 1,
    "distinctFamilies": 5,
    "twoStarLength": 288,
    "threeStarLength": 165,
    "shortestWin": 110,
    "measuredAt": "2026-09-13"
  },
  "a7-prop": {
    "solvable": true,
    "solutionBreadth": 0.0504,
    "precisionFloor": 45,
    "worstJitter": 0,
    "distinctFamilies": 2,
    "twoStarLength": 423,
    "threeStarLength": 300,
    "shortestWin": 230,
    "measuredAt": "2026-09-13"
  },
  "a8-jam": {
    "solvable": true,
    "solutionBreadth": 0.0824,
    "precisionFloor": 45,
    "worstJitter": 0,
    "distinctFamilies": 5,
    "twoStarLength": 300,
    "threeStarLength": 165,
    "shortestWin": 110,
    "measuredAt": "2026-09-13"
  },
  "a9-chute": {
    "solvable": true,
    "solutionBreadth": 0.2765,
    "precisionFloor": 65,
    "worstJitter": 1,
    "distinctFamilies": 6,
    "twoStarLength": 288,
    "threeStarLength": 165,
    "shortestWin": 86,
    "measuredAt": "2026-09-13"
  },
  "a10-switch": {
    "solvable": true,
    "solutionBreadth": 0.1827,
    "precisionFloor": 65,
    "worstJitter": 2,
    "distinctFamilies": 6,
    "twoStarLength": 295,
    "threeStarLength": 192,
    "shortestWin": 110,
    "measuredAt": "2026-09-13"
  }
};
