// Solver CLI.
//
//   node tools/solver            analyse every level, write measured thresholds
//   node tools/solver a2-gap     analyse one
//   node tools/solver --density 0.6   coarser sweep (faster)
//   node tools/solver --check    gates only, no write — the regression mode
//
// Exits non-zero if any level fails a HARD gate, so it can sit in CI or in
// `npm test` as the thing that catches a physics tune breaking a level.

import { writeFileSync } from 'node:fs';
import { LEVELS, HELD, ALL_LEVELS, getLevel } from '../../js/levels.js';
import { analyse, gradeLevel } from './solve.js';

const argv = process.argv.slice(2);
const flag = (name, def) => {
  const i = argv.indexOf(name);
  return i >= 0 ? (argv[i + 1] ?? true) : def;
};
const density = Number(flag('--density', 1));
const checkOnly = argv.includes('--check');
const target = argv.find((a) => !a.startsWith('--') && !/^[\d.]+$/.test(a));
const levels = target ? [getLevel(target)] : ALL_LEVELS;
const heldIds = new Set(HELD.map((h) => h.level.id));

const pct = (v) => `${(v * 100).toFixed(1)}%`;
let hardFailures = 0;
const results = {};

for (const level of levels) {
  const t0 = Date.now();
  process.stdout.write(`\n${level.id}  (${level.verb})  sweeping… `);
  const a = analyse(level, { density });
  results[level.id] = a;
  process.stdout.write(`${((Date.now() - t0) / 1000).toFixed(1)}s\n`);

  console.log(`  region          ${Math.round(a.region.w)}x${Math.round(a.region.h)} at (${Math.round(a.region.x)},${Math.round(a.region.y)})`);
  console.log(`  strokes         ${a.total} tried, ${a.rejected} rejected, ${a.plausible} plausible`);
  console.log(`  wins            ${a.wins}  →  breadth ${pct(a.solutionBreadth)}   [gate 2%–40%]`);
  console.log(`  families        ${a.distinctFamilies} distinct: ${JSON.stringify(a.familyBreakdown)}`);
  console.log(`  failures        ${JSON.stringify(a.outcomes)}`);
  console.log(`  shortest win    ${a.shortestWin}u (${a.shortestWinFamily})`);
  console.log(`  precision floor ${a.precisionFloor}u   [gate ≥25u]`);
  console.log(`  hand-drawn wobble ${a.worstJitter} (path/net)   [gate ≤8]`);
  console.log(`  ★★ / ★★★        ${a.twoStarLength}u / ${a.threeStarLength}u   (60th/20th pct, MEASURED)`);

  const issues = gradeLevel(a);
  const held = heldIds.has(level.id);
  if (!issues.length) console.log(`  VERDICT         PASS${held ? ' (held — now clears, consider shipping)' : ''}`);
  for (const i of issues) {
    // A held level is expected to fail. It is reported, not counted: the suite
    // stays honest about the shipping set without going permanently red.
    const tag = held ? 'HELD     ' : (i.hard ? 'HARD FAIL' : 'WARN     ');
    console.log(`  ${tag}       ${i.msg}`);
    if (i.hard && !held) hardFailures++;
  }
}

if (!checkOnly) {
  const out = Object.fromEntries(Object.entries(results).filter(([id]) => !heldIds.has(id)).map(([id, a]) => [id, {
    solvable: a.solvable,
    solutionBreadth: Number(a.solutionBreadth.toFixed(4)),
    precisionFloor: a.precisionFloor,
    worstJitter: a.worstJitter,
    distinctFamilies: a.distinctFamilies,
    twoStarLength: a.twoStarLength,
    threeStarLength: a.threeStarLength,
    shortestWin: a.shortestWin,
    measuredAt: new Date().toISOString().slice(0, 10),
  }]));
  const body = `// GENERATED by tools/solver — do not edit by hand.
//
// Star thresholds here are MEASURED percentiles of winning stroke lengths
// across the plausible stroke space, not guesses. Re-run after any physics
// change: \`node tools/solver\`.

export const SOLVER = ${JSON.stringify(out, null, 2)};
`;
  writeFileSync(new URL('../../js/solverData.js', import.meta.url), body);
  console.log(`\nwrote js/solverData.js for ${Object.keys(out).length} level(s)`);
}

console.log(hardFailures ? `\n${hardFailures} HARD GATE FAILURE(S)\n` : '\nALL LEVELS PASS THE GATES\n');
process.exit(hardFailures ? 1 : 0);
